// Metadata created by nebel
//

[id="mysql-purges-binlog-files"]
= MySQL purges binlog files
//In the title of a reference module, include nouns that are used in the body text. For example, "Keyboard shortcuts for ___" or "Command options for ___." This helps readers and search engines find the information quickly.

A short introductory paragraph is required for the reference module.
It will provide an overview of the module.

A reference module provide data that users might want to look up, but do not need to remember.
It has a very strict structure, often in the form of a list or a table.
A well-organized reference module enables users to scan it quickly to find the details they want.
AsciiDoc markup to consider for reference data:

.Unordered list
* For more details on writing reference modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles.
For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].

.Labeled list
Term 1:: Definition
Term 2:: Definition

.Table
[options="header"]
|====
|Column 1|Column 2|Column 3
|Row 1, column 1|Row 1, column 2|Row 1, column 3
|Row 2, column 1|Row 2, column 2|Row 2, column 3
|====
