-- Connect
--CONN c##dbzuser/dbz@//localhost:1521/ORCLCDB
CONN c##dbzuser/dbz@//localhost:1521/ORCLPDB1
-- Create data set
CREATE TABLE PEOPLE(name VARCHAR2(10));
ALTER TABLE PEOPLE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

CREATE TABLE debezium_table1 (id NUMERIC(9,0) NOT NULL, name VARCHAR2(1000), PRIMARY KEY (id));
ALTER TABLE debezium_table1 ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

CREATE TABLE debezium_table2 (id NUMERIC(9,0) NOT NULL, name VARCHAR2(1000), PRIMARY KEY (id));
ALTER TABLE debezium_table2 ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

CREATE TABLE debezium_table3 (id NUMERIC(9,0) NOT NULL, name VARCHAR2(1000), birth_date date, PRIMARY KEY (id));
ALTER TABLE debezium_table3 ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

CREATE TABLE TEST
(COLUMN1 NUMBER(19) NOT NULL,
COLUMN2 VARCHAR2(255),
PRIMARY KEY (COLUMN1));
ALTER TABLE TEST ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

CREATE TABLE DEBEZIUM_TEST
(id NUMBER(19) NOT NULL,
col1 NUMERIC(4,2),
col2 VARCHAR2(255) DEFAULT 'debezium' NOT NULL,
col3 NVARCHAR2(255) NOT NULL,
col4 CHAR(4),
col5 NCHAR(4),
col6 FLOAT(126),
col7 DATE,
col8 TIMESTAMP,
col9 blob,
col10 clob,
col12 NUMBER(1,0),
col13 DATE NOT NULL,
PRIMARY KEY (id));
ALTER TABLE DEBEZIUM_TEST ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO PEOPLE (name) VALUES ('Larry');
INSERT INTO PEOPLE (name) VALUES ('Bruno');
INSERT INTO PEOPLE (name) VALUES ('Gerald');

COMMIT;
