language: java
cache:
  directories:
  - $HOME/.m2/repository

sudo: required

jdk:
  - oraclejdk8

services:
  - docker

# First stop MySQL and PostgreSQL that run by default (see DBZ-163). Then check Docker status. Finally,
# install Maven 3.3.9, since the Jolokia Maven plugin requires 3.2.1 or later but Travis current runs 3.1.x
before_install:
  - sudo service mysql-5.6 stop || sudo service mysql stop
  - sudo /etc/init.d/postgresql stop
  - docker -v
  - docker ps -a
  - wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
  - unzip -qq apache-maven-3.3.9-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
  - mvn -version

# By default Travis will install dependencies before it runs a build, and with Maven projects that
# means running an install build without tests. We don't need to do this, and it actually causes problems.
# So skip it...
install: true

after_install:
  - docker ps -a

script: 
  - mvn clean install -Passembly -Dversion.postgres.server=9.6-devel
  - mvn install -pl debezium-connector-postgres -Pwal2json-decoder -Dversion.postgres.server=9.6-devel

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/44c51b6da8c2bec32645
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
