steps:
  - name: google/cloud-sdk
    entrypoint: "/bin/bash"
    args:
    - "-c"
    - |
      set -x 
      set -e
      set -o pipefail
      date
      if gsutil stat gs://debezium-maven-repo/$REPO_NAME.tar
        then gsutil cp gs://debezium-maven-repo/$REPO_NAME.tar - | tar -xf -
      fi
      date
  - name: "eu.gcr.io/confluent-kafka-development/jenkins-maven-gcp:11-3.6.3"
    args: ["/bin/bash", "-c", "mvn install -Dmaven.repo.local=./_m2/repository/ -DskipITs; ls ./_m2/repository/; ls ./_m2/repository/"]
    timeout: "8200s"
  - name: google/cloud-sdk
    entrypoint: "/bin/bash"
    args:
    - "-c"
    - |
      set -x 
      set -e
      set -o pipefail
      date
      tar -cf - ./_m2/ | gsutil cp - gs://debezium-maven-repo/$REPO_NAME.tar
      date
timeout: "8200s"
