steps:
  - name: google/cloud-sdk
    args: ["/bin/bash", "-c", "if gsutil ls gs://debezium-maven-repo/debezium/repository; then gsutil -m cp -R gs://debezium-maven-repo/database-schema-registry/repository /root/.m2/; fi" ]
  - name: "eu.gcr.io/confluent-kafka-development/jenkins-maven-gcp:11-3.6.3"
    args: ["/bin/bash", "-c", "cat /root/.m2/settings.xml ; mvn install -DskipITs"]
    timeout: "7200s"
  - name: google/cloud-sdk
    args: ['gsutil','-m', 'cp', '-r', '/root/.m2/repository/', 'gs://debezium-maven-repo/debezium/']
  - name: google/cloud-sdk
    args: ['gsutil','ls', 'gs://debezium-maven-repo/database-schema-registry/']
timeout: "7200s"