steps:
  - name: google/cloud-sdk
    entrypoint: "/bin/bash"
    args:
    - "-c"
    - |
      set -x 
      set -e
      set -o pipefail
      date
      if gsutil stat gs://debezium-maven-repo/$REPO_NAME/repository
        then mkdir -p ./_m2/
        gsutil -m cp -R gs://debezium-maven-repo/$REPO_NAME/repository ./_m2/
      fi
      date
  - name: "eu.gcr.io/confluent-kafka-development/jenkins-maven-gcp:11-3.6.3"
    args: ["/bin/bash", "-c", "mvn install -Dmaven.repo.local=./_m2/repository/ -DskipITs; ls ./_m2/repository/; ls ./_m2/repository/"]
    timeout: "8200s"
  - name: google/cloud-sdk
    entrypoint: "/bin/bash"
    args:
    - "-c"
    - |
      set -x 
      set -e
      set -o pipefail
      date
      if gsutil stat gs://debezium-maven-repo/$REPO_NAME/repository
        then gsutil -m cp -r ./_m2/repository gs://debezium-maven-repo/$REPO_NAME/
      fi
      date
timeout: "8200s"
