# Job definition to execute staging of Debezium product builds
---
- job:
    project-type: pipeline
    name: debezium-stage-prod
    display-name: Debezium Stage Product Artifacts
    description: Uploads product artifacts into stage location
    node: Slave
    properties:
      - build-discarder:
          num-to-keep: 5
    parameters:
      - string:
          name: BUILD_VERSION
          description: "Maven artifact id of the product binaries"
      - string:
          name: PRODUCT_VERSION
          description: "Product version"
      - string:
          name: USERNAME
          description: "Username to log to staging host"
      - password:
          name: PASSWORD
          description: "Password to log to staging host"
          default: "master"
      - string:
          name: CONNECTORS
          description: "The list of released connectors"
          default: "mysql postgres mongodb sqlserver"
      - bool:
          name: STAGE_FILES
          description: "When checked the uploaded artifacts are staged"
          default: "false"
      - string:
          name: SOURCE_MAVEN_REPO
          description: "Maven repository URL with product artifacts"
          default: "debezium-prod-repo"
      - string:
          name: TARGET_HOST
          description: "Staging host"
          type: secrettext
          default: "debezium-staging-url"
      - string:
          name: ARTIFACT_DIR
          description: "Staging directory"
          default: "/mnt/rcm-guest/staging/amq"
    dsl:
      !include-raw:
        - "scripts/prod-release-pipeline.groovy"
