pipeline {
    agent {
        label "jnlp-agent"
    }

    stages {
            stage('Checkout Job DSL definitions') {
                steps {
                    checkout([
                            $class           : 'GitSCM',
                            branches         : [[name: "${JOB_REPO_URL}"]],
                            userRemoteConfigs: [[url: "${JOB_REPO_BRANCH}"]],
                            extensions       : [[$class           : 'RelativeTargetDirectory',
                                                 relativeTargetDir: 'debezium'],
                                                 [$class: 'CloneOption', noTags: false, depth: 1, reference: '', shallow: true, timeout: 60]],
                    ])
                }
            }

            stage("Invoke Job DSL") {
                steps {
                    dir("${env.WORKSPACE}/jenkins") {
                        jobDsl targets: '**/**/*dsl.groovy',
                        removedJobAction: 'DISABLE',
                        removedViewAction: 'DELETE',
                        additionalClasspath: 'src \n **/**/*.groovy',
                        sandbox: true
                    }
                    dir("${env.WORKSPACE}/debezium") {
                        jobDsl targets: 'jenkins-jobs/job-dsl/**/*.groovy',
                        removedJobAction: 'DELETE',
                        removedViewAction: 'DELETE'
                    }
                }
            }
        }
}
