// Metadata created by nebel
//

[id="configure-the-mysql-connector_{context}"]
= Configuring the MySQL connector

ifdef::community[]
Typically, you configure the {prodname} MySQL connector in a `.json` file using the configuration properties available for the connector.

.Prerequisites
* You should have completed the {link-prefix}:{link-mysql-connector}#install-the-mysql-connector_{context}[installation process] for the connector.

.Procedure

. Set the `"name"` of the connector in the `.json` file.
. Set the configuration properties that you require for your {prodname} MySQL connector.

TIP: For a complete list of configuration properties, see {link-prefix}:{link-mysql-connector}#mysql-connector-configuration-properties_{context}[MySQL connector configuration properties].

.MySQL connector example configuration

[source,json]
----
{
  "name": "inventory-connector", <1>
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector", <2>
    "database.hostname": "192.168.99.100", <3>
    "database.port": "3306", <4>
    "database.user": "debezium-user", <5>
    "database.password": "debezium-user-pw", <6>
    "database.server.id": "184054", <7>
    "database.server.name": "fullfillment", <8>
    "database.whitelist": "inventory", <9>
    "database.history.kafka.bootstrap.servers": "kafka:9092", <10>
    "database.history.kafka.topic": "dbhistory.fullfillment", <11>
    "include.schema.changes": "true" <12>
  }
}
----

== Example configuration properties explained

. The connector's name when registered with the Kafka Connect service.
. The connector's class name.
. The MySQL server address.
. The MySQL server port number.
. The MySQL user with the appropriate privileges.
. The MySQL user's password.
. The unique ID of the connector.
. The logical name of the MySQL server or cluster.
. A list of all databases hosted by the specified server.
. A list of Kafka brokers that the connector uses to write and recover DDL statements to the database history topic.
. The name of the database history topic.
. The flag that specifies if the connector should generate on the schema change topic named `fulfillment` events with DDL changes that can be used by consumers.

endif::community[]
ifdef::product[]

Typically, you configure the {prodname} MySQL connector in a `.yaml` file using the configuration properties available for the connector.

.Prerequisites
* You should have completed the {link-prefix}:{link-mysql-connector}#install-the-mysql-connector_{context}[installation process] for the connector.

.Procedure

. Set the `"name"` of the connector in the `.yaml` file.

. Set the configuration properties that you require for your {prodname} MySQL connector.

TIP: For a complete list of configuration properties, see {link-prefix}:{link-mysql-connector}#mysql-connector-configuration-properties_{context}[MySQL connector configuration properties].

.MySQL connector example configuration

[source,yaml,options="nowrap"]
----
  apiVersion: kafka.strimzi.io/v1alpha1
  kind: KafkaConnector
  metadata:
    name: inventory-connector  // <1>
    labels:
      strimzi.io/cluster: my-connect-cluster
  spec:
    class: io.debezium.connector.mysql.MySqlConnector
    tasksMax: 1  // <2>
    config:  // <3>
      database.hostname: mysql  // <4>
      database.port: 3306
      database.user: debezium
      database.password: dbz
      database.server.id: 184054  // <5>
      database.server.name: dbserver1  // <5>
      database.whitelist: inventory  // <6>
      database.history.kafka.bootstrap.servers: my-cluster-kafka-bootstrap:9092  // <7>
      database.history.kafka.topic: schema-changes.inventory  // <7>
----
<1> The name of the connector.
<2> Only one task should operate at any one time.
Because the MySQL connector reads the MySQL server’s `binlog`,
using a single connector task ensures proper order and event handling.
The Kafka Connect service uses connectors to start one or more tasks that do the work,
and it automatically distributes the running tasks across the cluster of Kafka Connect services.
If any of the services stop or crash,
those tasks will be redistributed to running services.
<3> The connector’s configuration.
<4> The database host, which is the name of the container running the MySQL server (`mysql`).
<5> A unique server ID and name.
The server name is the logical identifier for the MySQL server or cluster of servers.
This name will be used as the prefix for all Kafka topics.
<6> Only changes in the `inventory` database will be detected.
<7> The connector will store the history of the database schemas in Kafka using this broker (the same broker to which you are sending events) and topic name.
Upon restart, the connector will recover the schemas of the database that existed at the point in time in the `binlog` when the connector should begin reading.

endif::product[]
