. Switch to the terminal running the HTTP Sink to see a _new_ fifth event.

+
--
By changing a record in the `customers` table, the {prodname} MySQL connector generated a new event.
You should see the change event at the end of the {prodname} server POST request log.

Here are the details of the _key_ for the _update_ event (formatted for readability):

[source,json,options="nowrap"]
----
  {
    "schema": {
      "type": "struct",
      "name": "tutorial.inventory.customers.Key",
      "optional": false,
      "fields": [
        {
          "field": "id",
          "type": "int32",
          "optional": false
        }
      ]
    },
    "payload": {
      "id": 1005
    }
  }
----

This _key_ is the same as the _key_ for the previous events.

Here is that new event's _value_.
There are no changes in the `schema` section, so only the `payload` section is shown (formatted for readability):

[source,json,options="nowrap",subs="+attributes"]
----
"payload": {
        "before": {
            "id": 1005,
            "first_name": "John",
            "last_name": "Tutorial",
            "email": "johntutorial@example.com"
        },
        "after": {
            "id": 1005,
            "first_name": "Johnathan",
            "last_name": "Tutorial",
            "email": "johnathantutorial@example.com"
        },
        "source": {
            "version": "3.7.0.Alpha1",
            "connector": "mysql",
            "name": "tutorial",
            "ts_ms": 1788868634000,
            "snapshot": "false",
            "db": "inventory",
            "sequence": null,
            "ts_us": 1788868634000000,
            "ts_ns": 1788868634000000000,
            "table": "customers",
            "server_id": 223344,
            "gtid": null,
            "file": "mysql-bin.000003",
            "pos": 749,
            "row": 0,
            "thread": 13,
            "query": null
        },
        "transaction": null,
        "op": "u",
        "ts_ms": 1788868634226,
        "ts_us": 1788868634226163,
        "ts_ns": 1788868634226163339
    }
----

The following list describes select fields in the preceding example of the payload of an `update` event value:

`before`::
The `before` field shows the values that were present in the row before the update.
The original `first_name` value is `Anne`.

`after`::
The `after` field shows the state of the row after the `update` event.
The `first_name` value is now `Anne Marie`.

`source`::
The `source` field structure has many of the same values as before, except that the `ts_sec` and `pos` fields have changed.
In some circumstances, the `file` value might also change.

`op`::
Shows the type of operation that the event describes.
The `u` value indicates that change was due to an `update` event.

`ts_ms`, `ts_us`, `ts_ns`::
Displays timestamps in milliseconds, microseconds, and nanoseconds that indicate when the connector processed the event.
The time is based on the system clock in the JVM that runs the Kafka Connect task.

By viewing the `payload` section, you can learn several important things about the _update_ event:

* By comparing the `before` and `after` structures, you can determine what actually changed in the affected row because of the commit.
* By reviewing the `source` structure, you can find information about MySQL's record of the change (providing traceability).
* By comparing the `payload` section of an event to other events in the same topic (or a different topic), you can determine whether the event occurred before, after, or as part of the same MySQL commit as another event.
--
