.Procedure

. Create a new file called `application.properties` in the `debezium-server/config/lib` directory and add the following to it:

+
--
----
debezium.sink.type=http
debezium.sink.http.url=http://127.0.0.1:8081
debezium.format.value=json
debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.offset.flush.interval.ms=0
debezium.source.database.hostname=localhost
debezium.source.database.port=3306
debezium.source.database.server.id=223344
debezium.source.database.user=debezium
debezium.source.database.password=dbz
debezium.source.topic.prefix=tutorial
debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=data/history.dat
debezium.source.database.include.list=inventory
quarkus.log.console.json=false
----
--
+

The following list describes the purpose of each configuration option shown above:

+
--
`debezium.sink.type=http`:: The type of sink to use
`debezium.sink.http.url=http://127.0.0.1:8081`:: The url that {prodname} server will stream change events to
`debezium.format.value=json`:: The format used to encode the value portion of the change events
`debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector`:: The connector class to use
`debezium.source.offset.storage.file.filename=data/offsets.dat`:: The location that the offsets are stored when not using Kafka
`debezium.source.offset.flush.interval.ms=0`:: Interal in milliseconds between each offset flush
`debezium.source.database.hostname=localhost`:: Host that the server is on
`debezium.source.database.port=3306`:: The port used to reach the MySQL database server
`debezium.source.database.server.id=223344`:: The MySQL database server's ID
`debezium.source.database.user=debezium`:: MySQL database server username
`debezium.source.database.password=dbz`:: MySQL database server password
`debezium.source.topic.prefix=tutorial`:: Change event topic prefix
`debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory`:: File history config
`debezium.source.schema.history.internal.file.filename=data/history.dat`:: Location of the history file
`debezium.source.database.include.list=inventory`:: The specific database to track on the server (you can also specify single tables, or exclude only tables you don't want)
`quarkus.log.console.json=false`:: Specifies Quarkus output format
--
+

.Further Configuration

* For a full list of configuration options for {prodname} server, visit {link-prefix}:{link-debezium-server}#debezium-server{prodname-server}
* For a full list of configuration options for the MySQL connector, visit {link-prefix}:{link-mysql-connector}#debezium-connector-for-mysql[{prodname} connector for MySQL].
