.Procedure

. Get the upstream default configuration for the {selected-sink} server we will use to receive change events from {prodname} server:

+
--
We will be using the https://hub.docker.com/_/httpd[Apache Httpd] container image as the base image for our {selected-sink} sink.
The following command copies the configuration file from the container to a file called `my-httpd.conf`.

[source,shell,options="nowrap",subs="+attributes"]
----
$ docker run --rm httpd:2.4 cat /usr/local/apache2/conf/httpd.conf > my-httpd.conf
----

You should also make a backup of the default configuration, which we will use to make sure the correct lines have been changed later.

[source,shell,options="nowrap"]
----
$ cp my-httpd.conf default-httpd.conf
----

We can now edit the `my-httpd.conf` file to allow us to see the full information of each change event (sent as POST requests to the URL we will specify in the Debezium server configuration file `application.properties` later.)
--

. Edit `my-httpd.conf` to load the `mod_dumpio` module and send its output to the terminal

+
--
We will use the https://httpd.apache.org/docs/current/mod/mod_dumpio.html[mod_dumpio] module to log the full information about each request the server receives, including the request body where the change event information is stored.

You will need to locate and edit the following lines in `my-httpd.conf`:

. `#LoadModule dumpio_module modules/mod_dumpio.so` > `LoadModule dumpio_module modules/mod_dumpio.so`.
Below this line, add `DumpIOInput On`

. `ErrorLog /proc/self/fd/2` > `ErrorLog /proc/self/fd/1` 

. `LogLevel warn` > `LogLevel dumpio:trace7`

`LoadModule dumpio_module modules/mod_dumpio.so`:: Loads the `mod_dumpio` module.
`ErrorLog /proc/self/fd/1`:: Specifies the file the ErrorLog is written to, in this case it is output to the container's standard output to allow us to view it in the terminal. For more information about `/proc/...` see https://man7.org/linux/man-pages/man5/proc.5.html[here]
`LogLevel dumpio:trace7`:: Loglevel to use, in this case we are using the `dumpio:trace7` level which will give us all the necessary request information.

To verify that the right changes have been made, run the following statement:
[source,shell,options="nowrap"]
----
$ diff default-httpd.conf my-httpd.conf
----

You should see output similar to the following:
[source,shell,options="nowrap"]
----
102c102,103
< #LoadModule dumpio_module modules/mod_dumpio.so
---
> LoadModule dumpio_module modules/mod_dumpio.so
> DumpIOInput On
317c318
< ErrorLog /proc/self/fd/2
---
> ErrorLog /proc/self/fd/1 
324c325
< LogLevel warn
---
> LogLevel dumpio:trace7
----

The first value for each is the original one from `default-httpd.conf`, while the second one is our new value in `my-httpd.conf`.
--

. Create a Dockerfile which we will use to build a custom `httpd:2.4` container image using our configuration.

+
--
In the same directory as your `my-httpd.conf` file, create a new file called `Dockerfile` (no file extension necessary). In this file, put the following:

.Dockerfile
[source,dockerfile,options="nowrap"]
----
FROM httpd:2.4
COPY ./my-httpd.conf /usr/local/apache2/conf/httpd.conf
----

`FROM httpd:2.4`:: Defines the base image
`COPY ./my-httpd.conf /usr/local/apache2/conf/httpd.conf`:: Copies our custom configuration file into the container so it can be used by the server.
--

. Build the custom `httpd:2.4` image using the Dockerfile

+
--
Run the following command to build the container image we will use.

[source,shell,options="nowrap"]
----
$ docker build -t example-httpd .
----

--

. Open a new terminal and use it to start the {selected-sink} server that will receive change events from {prodname} server in a container.

+
--
This command runs a new container using our `example-httpd` image:

[source,shell,options="nowrap",subs="+attributes"]
----
$ docker run -it -rm --name httpsink -p 8081:80 -v $(pwd):/user/local/apache2/htdocs example-httpd
----

The following list describes the purpose of parameters in the preceding command:

`-it`:: The container is interactive, which means the terminal's standard input and output are attached to the container.
`--rm`:: The container will be removed when it is stopped.
`--name httpsink`:: The name of the container.
`-p 8081:80`:: Maps port `8081` in the container to port `80` on the Docker host so that applications outside of the container can communicate with {prodname} server.
`-v $(pwd):/user/local/apache2/htdocs`:: Mounts the container's filesystem to a volume on the host machine.
`quay.io/debezium/example-httpd:{debezium-docker-label}`:: The Docker label indicating the container image we are using, in this case an example configuration of https://github.com/docker-library/httpd/blob/4da43810a4429c552e19c43f8e513248c34cfc84/2.4/Dockerfile[`httpd:2.4`].

You should see output similar to the following:

[source,shell,options="nowrap"]
----
[mpm_event:notice] [pid 1:tid 1] AH00489: Apache/2.4.68 (Unix) configured -- resuming normal operations
[core:notice] [pid 1:tid 1] AH00094: Command line: 'httpd -D FOREGROUND'
----

As the server receives change events it will output them here.
--

. Verify that the server started by running the following command:

+
[source,shell,options="nowrap"]
----
$ curl http://localhost:8081
----
+

You should see something like the following:

+
[source,html,options="nowrap"]
----
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<title>It works! Apache httpd</title>
</head>
<body>
<p>It works!</p>
</body>
</html>
----
+

Alternatively, you can test that it works by visiting `http://localhost:8081` in a web browser.
The preceding response shows that the HTTP sink started successfully and is ready to receive change events from {prodname} server.