/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":debezium-quarkus-outbox-reactive"))
    api(libs.io.quarkus.quarkus.hibernate.reactive)
    api(libs.io.quarkus.quarkus.reactive.pg.client)
    testImplementation(libs.io.quarkus.quarkus.vertx)
    testImplementation(libs.io.quarkus.quarkus.resteasy)
    testImplementation(libs.io.quarkus.quarkus.opentelemetry)
    testImplementation(libs.io.quarkus.quarkus.junit5)
    testImplementation(libs.io.quarkus.quarkus.junit5.mockito)
    testImplementation(libs.io.quarkus.quarkus.test.vertx)
    testImplementation(libs.org.assertj.assertj.core.x1)
    testImplementation(libs.org.testcontainers.testcontainers.x1)
    testImplementation(libs.org.testcontainers.postgresql.x1)
    testImplementation(project(":debezium-quarkus-outbox-reactive-deployment"))
}

description = "Debezium Quarkus :: Outbox Reactive :: Integration Tests"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
