name: "Build JDBC"
description: "Builds the Debezium JDBC connector"

inputs:
  maven-cache-key:
    description: "The maven build cache key"
    required: true
  shell:
    description: "The shell to use"
    required: false
    default: bash

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-java

    - uses: ./.github/actions/maven-cache
      with:
       key: ${{ inputs.maven-cache-key }}

    - name: Build JDBC
      shell: ${{ inputs.shell }}
      run: >
        ./mvnw clean install -B -pl debezium-connector-jdbc -am
        -Passembly        
        -Dtest.tags=it-sqlserver,e2e-sqlserver,it-postgresql,e2e-postgresql,it-mysql,e2e-mysql
        -Dcheckstyle.skip=true
        -Dformat.skip=true
        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        -Dmaven.wagon.http.pool=false
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
        -DfailFlakyTests=false        
