[id="viewing-create-event-{selected-sink}-sink"]
= Viewing a _create_ event

By viewing the output of the {selected-sink} sink container,
you can see how the MySQL connector captured _create_ events in the `inventory` database.
In this case, the _create_ events capture new customers being added to the database.

.Procedure

ifdef::community[]
. Open a the terminal window that the {selected-sink} sink is running in.
+
--
In this tutorial, once change event data is received it is sent to the container's standard output.
To achieve more appreciable functionality in production, you should instead create an API to consume and process events as they are received.

[NOTE]
====
If you are running the container in detatched mode, run the following command to view its logs:
[source,shell,options="nowrap",subs="+attributes"]
----
$ docker logs httpsink
----
====

The output displays the change events.
Since this is the first time a snapshot has been taken, there will be a lot of change events (one for each record in the database).
Each event is formatted in JSON as configured by the `debezium.format.value` property in `config\lib\application.properties`.

You should see a large output similar to the following:

[source,shell,options="nowrap"]
----
...
[dumpio:trace7] [pid 5:tid 15] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [speculative-nonblocking] 1 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 1 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): P
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 16 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): OST / HTTP/1.1\r\n
[pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 37 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): Connection: Upgrade, HTTP2-Settings\r\n
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 22 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): Content-Length: 2670\r\n
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 22 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): Host: 127.0.0.1:8081\r\n
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 66 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): HTTP2-Settings: AAEAAEAAAAIAAAAAAAMAAAAAAAQBAAAAAAUAAEAAAAYABgAA\r\n
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 14 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): Upgrade: h2c\r\n
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 37 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): User-Agent: Java-http-client/25.0.4\r\n
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 32 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): content-type: application/json\r\n
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 142 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): X-DEBEZIUM-__DEBEZIUM.CONTEXT.CONNECTORLOGICALNAME: eyJzY2hlbWEiOnsidHlwZSI6InN0cmluZyIsIm9wdGlvbmFsIjpmYWxzZX0sInBheWxvYWQiOiJ0dXRvcmlhbCJ9\r\n
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 131 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): X-DEBEZIUM-__DEBEZIUM.CONTEXT.CONNECTORNAME: eyJzY2hlbWEiOnsidHlwZSI6InN0cmluZyIsIm9wdGlvbmFsIjpmYWxzZX0sInBheWxvYWQiOiJteXNxbCJ9\r\n
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 167 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): X-DEBEZIUM-__DEBEZIUM.CONTEXT.RUNID: eyJzY2hlbWEiOnsidHlwZSI6InN0cmluZyIsIm9wdGlvbmFsIjpmYWxzZX0sInBheWxvYWQiOiIwMWEwODA3ZS1jZDBjLTc1NjEtYWI0Mi00Y2JmMjVhMmUzNWEifQ==\r\n
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 120 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): X-DEBEZIUM-__DEBEZIUM.CONTEXT.TASKID: eyJzY2hlbWEiOnsidHlwZSI6InN0cmluZyIsIm9wdGlvbmFsIjpmYWxzZX0sInBheWxvYWQiOiIwIn0=\r\n
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [getline-blocking] 0 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 2 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): \r\n
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(135): [client 192.168.0.63:35330] mod_dumpio: dumpio_in [readbytes-blocking] 2670 readbytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(58): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): 2670 bytes
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): {"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"product_id"},{"type":"int32","optional":false,"field":"quantity"}],"optional":true,"name":"tutorial.inventory.products_on_hand.Value","field":"before"},{"type":"struct","fields":[{"type":"int32","optional":false,"field":"product_id"},{"type":"int32","optional":false,"field":"quantity"}],"optional":true,"name":"tutorial.inventory.products_on_hand.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,first,first_in_data_collection,last_in_data_collection,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"},{"type":"string","optional":true,"field":"table"},{"type":"int64","optional":false,"field":"server_id"},{"type":"string","optional":true,"field":"gtid"},{"type":"string","optional":false,"field":"file"},{"type":"int64","optional":false,"field":"pos"},{"type":"int32","optional":false,"field":"row"},{"type":"int64","optional":true,"field":"thread"},{"type":"string","optional":true,"field":"query"}],"optional":false,"name":"io.debezium.connector.mysql.Source","version":1,"field":"source"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"},{"type":"string","optional":false,"field":"op"},{"type":"int64","option
[dumpio:trace7] [pid 5:tid 17] mod_dumpio.c(100): [client 192.168.0.63:35330] mod_dumpio:  dumpio_in (data-HEAP): al":true,"field":"ts_ms"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"}],"optional":false,"name":"tutorial.inventory.products_on_hand.Envelope","version":2},"payload":{"before":null,"after":{"product_id":109,"quantity":5},"source":{"version":"3.7.0.Alpha1","connector":"mysql","name":"tutorial","ts_ms":1788862192000,"snapshot":"last","db":"inventory","sequence":null,"ts_us":1788862192000000,"ts_ns":1788862192000000000,"table":"products_on_hand","server_id":0,"gtid":null,"file":"mysql-bin.000003","pos":157,"row":0,"thread":null,"query":null},"transaction":null,"op":"r","ts_ms":1788862192430,"ts_us":1788862192430525,"ts_ns":1788862192430525901}}
192.168.0.63 - - "POST / HTTP/1.1" 200 191
...
----

[NOTE]
====
The httpd server is configured to output the details of any requests it receives (change events are sent as POST requests), so any new events will automatically appear as long as the {selected-sink} sink container is running.
====
--
endif::community[]

ifdef::product[]

The change event data is located at the end of the request output, just above where `192.168.0.63 - - "POST / HTTP/1.1" 200 191` is.
--
endif::product[]

. In the terminal that is running the MySQL command line client, run the following statement:
+
--
[source,sql,options="nowrap"]
----
mysql> INSERT INTO customers (first_name, last_name, email) VALUES ('John', 'Tutorial', 'johntutorial@example.com');
Query OK, 1 row affected (0.01 sec)
----

The new change event that appears in the {selected-sink} sink terminal output should look something like the following:

[source,shell,options="nowrap"]
----
[dumpio:trace7] [pid 5:tid 28] mod_dumpio.c(100): [client 192.168.0.63:52070] mod_dumpio:  dumpio_in (data-HEAP): {"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"first_name"},{"type":"string","optional":false,"field":"last_name"},{"type":"string","optional":false,"field":"email"}],"optional":true,"name":"tutorial.inventory.customers.Value","field":"before"},{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"first_name"},{"type":"string","optional":false,"field":"last_name"},{"type":"string","optional":false,"field":"email"}],"optional":true,"name":"tutorial.inventory.customers.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,first,first_in_data_collection,last_in_data_collection,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"},{"type":"string","optional":true,"field":"table"},{"type":"int64","optional":false,"field":"server_id"},{"type":"string","optional":true,"field":"gtid"},{"type":"string","optional":false,"field":"file"},{"type":"int64","optional":false,"field":"pos"},{"type":"int32","optional":false,"field":"row"},{"type":"int64","optional":true,"field":"thread"},{"type":"string","optional":true,"field":"query"}],"optional":false,"name":"io.debezium.connector.mysql.Source","version":1,"field":"source"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optio
[dumpio:trace7] [pid 5:tid 28] mod_dumpio.c(100): [client 192.168.0.63:52070] mod_dumpio:  dumpio_in (data-HEAP): nal":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"}],"optional":false,"name":"tutorial.inventory.customers.Envelope","version":2},"payload":{"before":null,"after":{"id":1005,"first_name":"John","last_name":"Tutorial","email":"johntutorial@example.com"},"source":{"version":"3.7.0.Alpha1","connector":"mysql","name":"tutorial","ts_ms":1788868525000,"snapshot":"false","db":"inventory","sequence":null,"ts_us":1788868525000000,"ts_ns":1788868525000000000,"table":"customers","server_id":223344,"gtid":null,"file":"mysql-bin.000003","pos":392,"row":0,"thread":13,"query":null},"transaction":null,"op":"c","ts_ms":1788868525720,"ts_us":1788868525720655,"ts_ns":1788868525720655533}}
192.168.0.63 - - "POST / HTTP/1.1" 200 191
----
--

. For the last event, review the details of the _key_.
+
--
Here are the details of the _key_ of the last event (formatted for readability):

[source,json,options="nowrap"]
----
{
  "schema":{
    "type":"struct",
      "fields":[
        {
          "type":"int32",
          "optional":false,
          "field":"id"
        }
      ],
    "optional":false,
    "name":"tutorial.inventory.customers.Key"
  },
  "payload":{
    "id":1005
  }
}
----

The event has two parts: a `schema` and a `payload`.
The `schema` contains a Kafka Connect schema describing what is in the payload.
In this case, the payload is a `struct` named `tutorial.inventory.customers.Key` that is not optional and has one required field (`id` of type `int32`).

The `payload` has a single `id` field, with a value of `1005`.

By reviewing the _key_ of the event,
you can see that this event applies to the row in the `inventory.customers` table whose `id` primary key column had a value of `1005`.
--

. Review the details of the same event's _value_.
+
--
The event's _value_ shows that the row was created,
and describes what it contains (in this case, the `id`, `first_name`, `last_name`, and `email` of the inserted row).

Here are the details of the _value_ of the last event (formatted for readability):

[source,json,options="nowrap",subs="+attributes"]
----
{
    "schema": {
        "type": "struct",
        "fields": [
            {
                "type": "struct",
                "fields": [
                    {
                        "type": "int32",
                        "optional": false,
                        "field": "id"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "first_name"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "last_name"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "email"
                    }
                ],
                "optional": true,
                "name": "tutorial.inventory.customers.Value",
                "field": "before"
            },
            {
                "type": "struct",
                "fields": [
                    {
                        "type": "int32",
                        "optional": false,
                        "field": "id"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "first_name"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "last_name"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "email"
                    }
                ],
                "optional": true,
                "name": "tutorial.inventory.customers.Value",
                "field": "after"
            },
            {
                "type": "struct",
                "fields": [
                    {
                        "type": "string",
                        "optional": false,
                        "field": "version"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "connector"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "name"
                    },
                    {
                        "type": "int64",
                        "optional": false,
                        "field": "ts_ms"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "name": "io.debezium.data.Enum",
                        "version": 1,
                        "parameters": {
                            "allowed": "true,first,first_in_data_collection,last_in_data_collection,last,false,incremental"
                        },
                        "default": "false",
                        "field": "snapshot"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "db"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "sequence"
                    },
                    {
                        "type": "int64",
                        "optional": true,
                        "field": "ts_us"
                    },
                    {
                        "type": "int64",
                        "optional": true,
                        "field": "ts_ns"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "table"
                    },
                    {
                        "type": "int64",
                        "optional": false,
                        "field": "server_id"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "gtid"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "file"
                    },
                    {
                        "type": "int64",
                        "optional": false,
                        "field": "pos"
                    },
                    {
                        "type": "int32",
                        "optional": false,
                        "field": "row"
                    },
                    {
                        "type": "int64",
                        "optional": true,
                        "field": "thread"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "query"
                    }
                ],
                "optional": false,
                "name": "io.debezium.connector.mysql.Source",
                "version": 1,
                "field": "source"
            },
            {
                "type": "struct",
                "fields": [
                    {
                        "type": "string",
                        "optional": false,
                        "field": "id"
                    },
                    {
                        "type": "int64",
                        "optional": false,
                        "field": "total_order"
                    },
                    {
                        "type": "int64",
                        "optional": false,
                        "field": "data_collection_order"
                    }
                ],
                "optional": true,
                "name": "event.block",
                "version": 1,
                "field": "transaction"
            },
            {
                "type": "string",
                "optional": false,
                "field": "op"
            },
            {
                "type": "int64",
                "optional": true,
                "field": "ts_ms"
            },
            {
                "type": "int64",
                "optional": true,
                "field": "ts_us"
            },
            {
                "type": "int64",
                "optional": true,
                "field": "ts_ns"
            }
        ],
        "optional": false,
        "name": "tutorial.inventory.customers.Envelope",
        "version": 2
    },
    "payload": {
        "before": null,
        "after": {
            "id": 1005,
            "first_name": "John",
            "last_name": "Tutorial",
            "email": "johntutorial@example.com"
        },
        "source": {
            "version": "3.7.0.Alpha1",
            "connector": "mysql",
            "name": "tutorial",
            "ts_ms": 1788868525000,
            "snapshot": "false",
            "db": "inventory",
            "sequence": null,
            "ts_us": 1788868525000000,
            "ts_ns": 1788868525000000000,
            "table": "customers",
            "server_id": 223344,
            "gtid": null,
            "file": "mysql-bin.000003",
            "pos": 392,
            "row": 0,
            "thread": 13,
            "query": null
        },
        "transaction": null,
        "op": "c",
        "ts_ms": 1788868525720,
        "ts_us": 1788868525720655,
        "ts_ns": 1788868525720655533
    }
}
----

This portion of the event is much longer,
but like the event's _key_, it also has a `schema` and a `payload`.
The `schema` contains a schema named `tutorial.inventory.customers.Envelope` (version 2) that can contain five fields:

`before`::
An optional field that, if present, contains the state of the row _before_ the event occurred.
The structure will be described by the `tutorial.inventory.customers.Value` Kafka Connect schema,
which the `tutorial` connector uses for all rows in the `inventory.customers` table.
`after`::
An optional field that, if present, contains the state of the row _after_ the event occurred.
The structure is described by the same `tutorial.inventory.customers.Value` Kafka Connect schema used in `before`.
`source`::
A required field that contains a structure describing the source metadata for the event,
which in the case of MySQL, contains several fields:
the connector name, the name of the `binlog` file where the event was recorded, the position in that `binlog` file where the event appeared, the row within the event (if there is more than one), the names of the affected database and table, the MySQL thread ID that made the change, whether this event was part of a snapshot, and, if available, the MySQL server ID, and the timestamp in seconds.
`transaction`::

`op`::
A required field that contains a string value describing the type of operation.
Values for the MySQL connector are `c` for create (or insert), `u` for update, `d` for delete, and `r` for read (in the case of a snapshot).
`ts_ms`::
An optional field that, if present, contains the time (using the system clock in the JVM running the Kafka Connect task) at which the connector processed the event.

[NOTE]
====
The JSON representations of the events are much longer than the rows they describe.
This is because, with every event key and value, {prodname} server ships the _schema_ that describes the _payload_.
Over time, this structure may change.
However, having the schemas for the key and the value in the event itself makes it much easier for consuming applications to understand the messages, especially as they evolve over time.

The {prodname} MySQL connector constructs these schemas based upon the structure of the database tables.
If you use DDL statements to alter the table definitions in the MySQL databases,
the connector reads these DDL statements and updates its Kafka Connect schemas.
This is the only way that each event is structured exactly like the table from where it originated at the time the event occurred.
However, the Kafka topic containing all of the events for a single table might have events that correspond to each state of the table definition.

The JSON converter includes the key and value schemas in every message,
so it does produce very verbose events.
// The following condition can be removed when the downstream supports Avro.
ifdef::community[]
Alternatively, you can use xref:configuration/avro.adoc[Apache Avro] as a serialization format, which results in far smaller event messages.
This is because it transforms each schema into an Avro schema and stores the Avro schemas in a separate Schema Registry service.
Thus, when the Avro converter serializes an event message,
it places only a unique identifier for the schema along with an Avro-encoded binary representation of the value.
As a result, the serialized messages that are transferred over the wire and stored in the offsets file are far smaller than what you have seen here.
In fact, the Avro Converter is able to use Avro schema evolution techniques to maintain the history of each schema in the Schema Registry.
endif::community[]
====
--

. Compare the event's _key_ and _value_ schemas to the state of the `inventory` database.
In the terminal that is running the MySQL command line client, run the following statement:
+
--
[source,sql,options="nowrap"]
----
mysql> SELECT * FROM customers;
+------+------------+-----------+--------------------------+
| id   | first_name | last_name | email                    |
+------+------------+-----------+--------------------------+
| 1001 | Sally      | Thomas    | sally.thomas@acme.com    |
| 1002 | George     | Bailey    | gbailey@foobar.com       |
| 1003 | Edward     | Walker    | ed@walker.com            |
| 1004 | Anne       | Kretchmar | annek@noanswer.org       |
| 1006 | John       | Tutorial  | johntutorial@example.com |
+------+------------+-----------+--------------------------+
5 rows in set (0.00 sec)
----

This shows that the event records you reviewed match the records in the database.
--
