:attributes: _attributes
:context: cdc
include::../{attributes}.adoc[]
= {prodname} connector for MySQL

MySQL has a binary log (binlog) that records all operations in the order in which they are committed to the database. This includes changes to table schemas and the data within tables. MySQL uses the binlog for replication and recovery.

The {prodname} MySQL connector reads the binlog and produces change events for row-level `INSERT`, `UPDATE`, and `DELETE` operations and records the change events in a Kafka topic. Client applications read those Kafka topics.

As MySQL is typically set up to purge binlogs after a specified period of time, the MySQL connector performs and initial _consistent snapshot_ of each of your databases. The MySQL connector reads the binlog from the point at which the snapshot was made.

The following sections provide more detailed information on how the {prodname} MySQL connector functions, instructs you on how to set it up, as well as deploy and troubleshoot the connector.

== Supported MySQL topologies

.MySQL standalone
[%collapsible]
====
When a single MySQL server is used, the server must have the binlog enabled (_and optionally GTIDs enabled_) so that the MySQL connector can monitor it. This is often acceptable, since the binary log can also be used as an incremental backup. In this case, the MySQL connector always connects to and follows this standalone MySQL server instance.
====


* xref:overview-of-how-the-mysql-connector-works[Overview of how the MySQL connector works]
* xref:setup-the-mysql-server[Setting up MySQL server]
* xref:deploy-the-mysql-connector[Deploying the MySQL connector]
* xref:troubleshoot-the-mysql-connector[Troubleshooting the MySQL connector]

// assemblies

include::{assemblies}/cdc-mysql-connector/as_overview-of-how-the-mysql-connector-works.adoc[leveloffset=+1]

include::{assemblies}/cdc-mysql-connector/as_setup-the-mysql-server.adoc[leveloffset=+1]

include::{assemblies}/cdc-mysql-connector/as_deploy-the-mysql-connector.adoc[leveloffset=+1]

include::{assemblies}/cdc-mysql-connector/as_troubleshoot-the-mysql-connector.adoc[leveloffset=+1]
