[id="installing-debezium"]
= Installing {prodname}

:toc:
:toc-placement: macro
:sectanchors:
:linkattrs:
:icons: font

There are several ways to install and use {prodname}, depending on your architecture and requirements. We have documented the most common methods to deploy {prodname} components.

== Installation Methods

* xref:install-kafka-connect.adoc[Installing Kafka Connect Connectors] - Deploy {prodname} connectors via Apache Kafka Connect.
* Debezium Operator (Coming soon)
* Debezium Server (Coming soon)
* Debezium CLI (Coming soon)

== Using the {prodname} Libraries

Although {prodname} is intended to be used as turnkey services, all of JARs and other artifacts are available in https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.debezium%22[Maven Central].

We do provide a small library so applications can xref:development/engine.adoc[embed any Kafka Connect connector] and consume data change events read directly from the source system.
This provides a light weight system (since Kafka and Kafka Connect services are not needed), but as a consequence it is not as fault tolerant or reliable since the application must manage and maintain all state normally kept inside Kafka's distributed and replicated logs.
It's perfect for use in tests, and with careful consideration it may be useful in some applications.
