/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.io.quarkus.quarkus.hibernate.reactive)
    api(libs.io.quarkus.quarkus.opentelemetry)
    api(libs.io.quarkus.quarkus.vertx)
    api(project(":debezium-quarkus-outbox-common"))
}

description = "Debezium Quarkus :: Outbox Reactive :: Runtime"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
