include::../_attributes.adoc[]
= {prodname} Connector for MySQL

MySQL has a binary log (binlog) that records all operations in the order in which they are committed to the database. This includes changes to table schemas and the data within tables. MySQL uses the binlog for replication and recovery.

The {prodname} MySQL connector reads the binlog and produces change events for row-level `INSERT`, `UPDATE`, and `DELETE` operations and records the change events in a Kafka topic. Client applications read those Kafka topics.

As MySQL is typically set up to purge binlogs after a specified period of time, the MySQL connector performs and initial _consistent snapshot_ of each of your databases. The MySQL connector reads the binlog from the point at which the snapshot was made.

The following sections provide more detailed information on how the {prodname} MySQL connector functions, instructs you on how to set it up, as well as deploy and troubleshoot the connector.

* xref:overview-of-how-the-mysql-connector-works.adoc[Overview of how the MySQL connector works]
* xref:setup-the-mysql-server.adoc[Setting up MySQL server]
* xref:deploy-the-mysql-connector.adoc[Deploying the MySQL connector]
* xref:troubleshoot-the-mysql-connector.adoc[Troubleshooting the MySQL connector]
