/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":debezium-connector-binlog"))
    api(libs.org.mariadb.jdbc.mariadb.java.client)
    testImplementation(project(":debezium-connector-binlog"))
    testImplementation(project(":debezium-core"))
    testImplementation(project(":debezium-embedded"))
    testImplementation(project(":debezium-embedded"))
    testImplementation(project(":debezium-testing-testcontainers"))
    testImplementation(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.mil.nga.wkb)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.awaitility.awaitility)
    testImplementation(libs.io.confluent.kafka.connect.avro.converter)
    testImplementation(libs.io.apicurio.apicurio.registry.utils.converter)
    testImplementation(libs.org.testcontainers.testcontainers)
    testImplementation(libs.org.testcontainers.mariadb)
    testImplementation(libs.io.rest.assured.rest.assured)
    testImplementation(libs.org.apache.kafka.kafka.v2.v13)
    compileOnly(libs.org.apache.kafka.connect.api)
}

description = "Debezium Connector for MariaDB"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
