ARG BASE_IMAGE
ARG DEBEZIUM_VERSION
FROM ${BASE_IMAGE}
ARG DEBEZIUM_VERSION

ENV CONNECTOR="oracle"
ENV MAVEN_DEP_DESTINATION=$KAFKA_HOME/libs \
    ORACLE_JDBC_REPO="com/oracle/database/jdbc" \
    ORACLE_JDBC_GROUP="ojdbc8" \
    ORACLE_JDBC_VERSION="21.6.0.0" \
    ORACLE_JDBC_MD5=312e6f4ec9932bbf74a4461669970c4b

RUN docker-maven-download central "$ORACLE_JDBC_REPO" "$ORACLE_JDBC_GROUP" "$ORACLE_JDBC_VERSION" "$ORACLE_JDBC_MD5"

RUN echo "Installing Debezium connectors version: ${DEBEZIUM_VERSION}" ; \
MAVEN_REPOSITORY="https://repo1.maven.org/maven2/io/debezium" ; \
if [[ "${DEBEZIUM_VERSION}" == *-SNAPSHOT ]] ; then \
    MAVEN_REPOSITORY="https://oss.sonatype.org/content/repositories/snapshots/io/debezium" ; \
fi ; \
CONNECTOR_VERSION="${DEBEZIUM_VERSION}" ; \
for PACKAGE in {scripting,}; do \
    local CONNECTOR_VERSION="${DEBEZIUM_VERSION}" ; \
    if [[ "${DEBEZIUM_VERSION}" == *-SNAPSHOT ]] ; then \
        CONNECTOR_VERSION=$(curl --silent -fSL "${MAVEN_REPOSITORY}/debezium-${PACKAGE}/${DEBEZIUM_VERSION}/maven-metadata.xml" | awk -F'<[^>]+>' '/<extension>tar.gz<\/extension>/ {getline; print $2; exit}'); \
    fi ; \
    echo "Downloading and installing debezium-${PACKAGE}-${CONNECTOR_VERSION}.tar.gz ..." ; \
    curl --silent -fSL -o /tmp/package.tar.gz "${MAVEN_REPOSITORY}/debezium-${PACKAGE}/${DEBEZIUM_VERSION}/debezium-${PACKAGE}-${CONNECTOR_VERSION}.tar.gz" && \
    echo "Extracting debezium-${PACKAGE}-${CONNECTOR_VERSION}.tar.gz ..." && \
    tar -xzf /tmp/package.tar.gz -C $EXTERNAL_LIBS_DIR && \
    echo "Successfully installed debezium-${PACKAGE}-${CONNECTOR_VERSION}!" ; \
    rm -f /tmp/package.tar.gz ; \
done

COPY --chown=kafka:kafka debezium-connector-${CONNECTOR}-${DEBEZIUM_VERSION}-plugin.tar.gz /tmp/plugin.tar.gz

RUN tar -xvzf /tmp/plugin.tar.gz -C ${KAFKA_CONNECT_PLUGINS_DIR}/ ; rm -f /tmp/plugin.tar.gz
