/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":debezium-core"))
    api(project(":debezium-storage-kafka"))
    api(project(":debezium-storage-file"))
    api(project(":debezium-ddl-parser"))
    api(libs.com.oracle.database.jdbc.ojdbc8)
    api(libs.org.antlr.antlr4.runtime)
    api(libs.org.infinispan.infinispan.core.jakarta)
    api(libs.org.infinispan.infinispan.client.hotrod.jakarta)
    api(libs.com.oracle.database.nls.orai18n)
    api(libs.com.google.protobuf.protobuf.java)
    api(libs.com.google.protobuf.protobuf.java.util)
    testImplementation(project(":debezium-core"))
    testImplementation(project(":debezium-embedded"))
    testImplementation(project(":debezium-embedded"))
    testImplementation(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.awaitility.awaitility)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(project(":debezium-testing-testcontainers"))
    testImplementation(libs.io.rest.assured.rest.assured)
    testImplementation(libs.io.confluent.kafka.connect.avro.converter)
    testImplementation(libs.io.apicurio.apicurio.registry.utils.converter)
    testImplementation(libs.org.apache.kafka.kafka.v2.v13)
    compileOnly(libs.org.apache.kafka.connect.api)
    compileOnly(libs.org.slf4j.slf4j.api)
    compileOnly(libs.org.infinispan.protostream.protostream.processor)
    compileOnly(libs.com.oracle.database.xml.xdb)
    compileOnly(libs.com.oracle.database.xml.xmlparserv2)
}

description = "Debezium Connector for Oracle"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
