/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.io.quarkus.quarkus.jackson)
    api(libs.io.quarkus.quarkus.hibernate.orm)
    api(libs.io.quarkus.quarkus.opentelemetry)
    api(libs.io.smallrye.jandex)
    api(project(":debezium-api"))
    testImplementation(libs.io.quarkus.quarkus.junit5.internal)
}

description = "Debezium Quarkus :: Outbox :: Runtime :: Common"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
