name: "Build Quarkus Extensions"
description: "Builds the Debezium Quarkus Extensions"

inputs:
  maven-cache-key:
    description: "The maven build cache key"
    required: true
  shell:
    description: "The shell to use"
    required: false
    default: bash

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-java

    - uses: ./.github/actions/maven-cache
      with:
        key: ${{ inputs.maven-cache-key }}

    - name: Build Debezium Quarkus Extensions
      shell: ${{ inputs.shell }}
      run: >
        ./mvnw clean install -B -pl :quarkus-debezium-parent -am -amd 
        -Dnative