/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.io.quarkus.quarkus.hibernate.orm.deployment)
    api(libs.io.quarkus.quarkus.jackson.deployment)
    api(project(":debezium-quarkus-outbox-deployment-common"))
    api(project(":debezium-quarkus-outbox"))
    testImplementation(libs.io.quarkus.quarkus.opentelemetry)
}

description = "Debezium Quarkus :: Outbox :: Deployment"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
