:page-aliases: configuration/header-to-value.adoc
// Category: debezium-using
// Type: assembly
// ModuleID: header-to-value
// Title: Moves or copies headers into the record value
[id="header-to-value"]
= HeaderToValue

:toc:
:toc-placement: macro
:linkattrs:
:icons: font
:source-highlighter: highlight.js

toc::[]

This SMT permits to copy or move headers to record value. Supports multiple headers and also nesting on the value through dot notation.

// Type: concept
// Title: Example: Basic configuration of the {prodname} partition routing SMT
// ModuleID: basic-configuration-of-the-debezium-partition-routing-smt
[[example-header-to-value]]
== Example

This configuration snippet shows how to use `HeaderToValue` to move the header `event_timestamp` and `key` in the record’s header into the record value. The transform removes the fields from the record header. If you want to keep the fields in the record header, use the operation copy instead of move.

[source]
----
transforms=moveHeadersToValue
transforms.moveHeadersToValue.type=io.debezium.transforms.HeaderToValue
transforms.moveHeadersToValue.headers=event_timestamp,key
transforms.moveHeadersToValue.fields=timestamp,source.id
transforms.moveHeadersToValue.operation=move
----

Before:

* Record header
[source]
----
{
    "header_x": 0,
    "event_timestamp": 1626102708861,
    "key": 100,
}
----
* Record value
[source]
----
{
        "before": null,
        "after": {
            "id": 1,
            "first_name": "Anne",
            "last_name": "Kretchmar",
            "email": "annek@noanswer.org"
        },
        "source": {
            "version": "2.1.3.Final",
            "connector": "postgresql",
            "name": "PostgreSQL_server",
            "ts_ms": 1559033904863,
            "snapshot": true,
            "db": "postgres",
            "sequence": "[\"24023119\",\"24023128\"]"
            "schema": "public",
            "table": "customers",
            "txId": 555,
            "lsn": 24023128,
            "xmin": null
        },
        "op": "c",
        "ts_ms": 1559033904863
    }
----

After:

* Record header
[source, json]
----
{
    "header_x": 0
}
----
* Record value
[source, json]
----
{
        "before": null,
        "after": {
            "id": 1,
            "first_name": "Anne",
            "last_name": "Kretchmar",
            "email": "annek@noanswer.org"
        },
        "source": {
            "version": "2.1.3.Final",
            "connector": "postgresql",
            "name": "PostgreSQL_server",
            "ts_ms": 1559033904863,
            "snapshot": true,
            "db": "postgres",
            "sequence": "[\"24023119\",\"24023128\"]"
            "schema": "public",
            "table": "customers",
            "txId": 555,
            "lsn": 24023128,
            "xmin": null,
            "id": 100
        },
        "op": "c",
        "ts_ms": 1559033904863,
        "event_timestamp": 1626102708861
    }
----

// Type: reference
// ModuleID: options-for-configuring-the-header-to-value-transformation
// Title: Options for configuring the HeaderToValue transformation
[[header-to-value-configuration-options]]
== Configuration options

The following table lists the configuration options that you can use with the `HeaderToValue` SMT.

.HeaderToValue SMT configuration options
[cols="14%a,40%a,10%a, 16%a, 16%a, 10%a"]
|===
|Property
|Description
|Type
|Default
|Valid Values
|Importance

|[[header-to-value-headers]]<<header-to-value-headers, `headers`>>
|A comma-separated list of header names in the record whose values are to be copied or moved to record value.
|list
|
|non-empty list
|high
|[[header-to-value-fields]]<<header-to-value-fields, `fields`>>
|A comma-separated list of field names, in the same order as the header names listed in the headers configuration property. Supports nesting using dot notation.
|list
|
|non-empty list
|high
|[[header-to-value-operation]]<<header-to-value-operation, `operation`>>
|Either `move` if the fields are to be moved to the value (removed from the headers), or `copy` if the fields are to be copied to the value (retained in the headers).
|string
|
|move or copy
|high
|===
