// Metadata created by nebel
//
// UserStory:

[id="introduction-debezium"]
= Introduction to {prodname}

{prodname} is a distributed platform that converts information from your existing databases into event streams, enabling applications to detect, and immediately respond to row-level changes in the databases.

{prodname} is built on top of http://kafka.apache.org[Apache Kafka] and provides {link-kafka-docs}.html#connect[Kafka Connect] compatible connectors that capture changes from database management systems.
{prodname} records the history of the data changes that occur in a database in Kafka logs.
Consuming applications can then read each change event record from the log, in order.
By taking advantage of Kafka's reliable streaming platform, {prodname} makes it possible for your application to easily consume all of the events that occur in a database correctly and completely.
Even if your application stops unexpectedly, or loses its connection, it does not miss events that occur during the outage.
After the application restarts, it resumes reading from the log from the point where it left off.

{prodname} includes multiple connectors, which share similar capabilities.
The tutorial that follows focuses on the {link-prefix}:{link-mysql-connector}#debezium-connector-for-mysql[MySQL connector].
