// Metadata created by nebel
//
// ParentAssemblies: assemblies/tutorial/as_using-debezium-monitor-mysql-database.adoc
// UserStory:

[id="registering-connector-monitor-inventory-database"]
= Registering a connector to monitor the `inventory` database

By registering the {prodname} MySQL connector,
the connector will start monitoring the MySQL database server's `binlog`.
The `binlog` records all of the database's transactions (such as changes to individual rows and changes to the schemas).
When a row in the database changes,
{prodname} generates a change event.

[NOTE]
====
In a production environment, you would typically either use the Kafka tools to manually create the necessary topics, including specifying the number of replicas,
or you'd use the Kafka Connect mechanism for customizing the settings of xref:{link-topic-auto-creation}[auto-created] topics.
However, for this tutorial, Kafka is configured to automatically create the topics with just one replica.
====

.Prerequisites

* You are familiar with the configuration options that are available for the connector.

.Procedure

. Review the configuration of the {prodname} MySQL connector that you will register.
+
--
In the next step, you will register the connector that is defined by the following configuration:

[source,json,options="nowrap"]
----
{
  "name": "inventory-connector",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "tasks.max": "1",
    "database.hostname": "mysql",
    "database.port": "3306",
    "database.user": "debezium",
    "database.password": "dbz",
    "database.server.id": "184054",
    "topic.prefix": "dbserver1",
    "database.include.list": "inventory",
    "schema.history.internal.kafka.bootstrap.servers": "kafka:9092",
    "schema.history.internal.kafka.topic": "schema-changes.inventory"
  }
}
----

The following list describes select fields in the preceding example of a connector configuration:

`name`::
Specifies the name of the connector.

`config`::
The connector's configuration.

`tasks.max`::
Specifies the number of tasks that the connector can operate at one time.
Only one task should operate at any one time.
Because the MySQL connector reads the MySQL server's `binlog`, using a single connector task ensures proper order and event handling.
The Kafka Connect service uses connectors to start one or more tasks to perform work,
and it automatically distributes the running tasks across the cluster of Kafka Connect services.
If any of the services stop or crash, tasks are redistributed to running services.

`database.hostname`::
Specifies the database host, which is the name of the container that runs the MySQL server (`mysql`).
Docker manipulates the network stack within the containers so that each linked container can be resolved with `/etc/hosts` using the container name for the host name.
If MySQL were running on a normal network, you would specify the IP address or resolvable host name for this value.

`database.server.id`::
A unique topic prefix.

`topic.prefix`::
Specifies the unique topic prefix for the database server or cluser.
This name is as the prefix for all Kafka topics that receive change event records from the connector.

`database.include.list`::
Specifies the names of the databases from which the connector captures changes.
This connector captures changes from the `inventory` database only.

`schema.history.internal.kafka.bootstrap.servers`::
Specifies that the connector uses `kafka:9092` as its Kafka broker to connect to the database schema history topic to write or read DDL statements.
After a connector restarts, it recovers the database schemas that existed in the binlog at the point in time when the connector stopped.

`schema.history.internal.kafka.topic`::
Specifies the name of the topic in which the connector stores its database schema history.
This topic is for internal use only and is not for direct use by consumers.

For more information, see xref:{link-mysql-connector}#mysql-connector-properties[MySQL connector configuration properties].
--

ifdef::community[]
[NOTE]
====
For security reasons, you shouldn't put passwords or other secrets in plain text into connector configurations.
Instead, any secrets should be externalized via the mechanism defined in https://cwiki.apache.org/confluence/display/KAFKA/KIP-297%3A+Externalizing+Secrets+for+Connect+Configurations[KIP-297]("Externalizing Secrets for Connect Configurations").
====
endif::community[]

. Open a new terminal, and use the `curl` command to register the {prodname} MySQL connector.
+
--
This command uses the Kafka Connect service's API to submit a `POST` request against the `/connectors` resource with a JSON document that describes the new connector (called `inventory-connector`).

This command uses `localhost` to connect to the Docker host.
If you are using a non-native Docker platform,
replace `localhost` with the IP address of of your Docker host.

[source,shell,options="nowrap"]
----
$ curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/ -d '{ "name": "inventory-connector", "config": { "connector.class": "io.debezium.connector.mysql.MySqlConnector", "tasks.max": "1", "database.hostname": "mysql", "database.port": "3306", "database.user": "debezium", "database.password": "dbz", "database.server.id": "184054", "topic.prefix": "dbserver1", "database.include.list": "inventory", "schema.history.internal.kafka.bootstrap.servers": "kafka:9092", "schema.history.internal.kafka.topic": "schemahistory.inventory" } }'
----

ifdef::windows[]
[NOTE]
====
Windows users may need to escape the double-quotes.
For example:

[source,shell,options="nowrap"]
----
$ curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/ -d '{ \"name\": \"inventory-connector\", \"config\": { \"connector.class\": \"io.debezium.connector.mysql.MySqlConnector\", \"tasks.max\": \"1\", \"database.hostname\": \"mysql\", \"database.port\": \"3306\", \"database.user\": \"debezium\", \"database.password\": \"dbz\", \"database.server.id\": \"184054\", \"topic.prefix\": \"dbserver1\", \"database.include.list\": \"inventory\", \"schema.history.internal.kafka.bootstrap.servers\": \"kafka:9092\", \"schema.history.internal.kafka.topic\": \"schemahistory.inventory\" } }'
----

Otherwise, you might see an error like the following:

[source,json,options="nowrap"]
----
{"error_code":500,"message":"Unexpected character ('n' (code 110)): was expecting double-quote to start field name\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 4]"}
----
====
endif::[]
--

ifdef::community[]
[NOTE]
====
If you use Podman, run the following command:
[source,shell,options="nowrap",subs="+attributes"]
----
$ curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/ -d '{ "name": "inventory-connector", "config": { "connector.class": "io.debezium.connector.mysql.MySqlConnector", "tasks.max": "1", "database.hostname": "0.0.0.0", "database.port": "3306", "database.user": "debezium", "database.password": "dbz", "database.server.id": "184054", "topic.prefix": "dbserver1", "database.include.list": "inventory", "schema.history.internal.kafka.bootstrap.servers": "0.0.0.0:9092", "schema.history.internal.kafka.topic": "schemahistory.inventory" } }'
----
====
endif::community[]

. Verify that `inventory-connector` is included in the list of connectors:
+
--
[source,shell,options="nowrap"]
----
$ curl -H "Accept:application/json" localhost:8083/connectors/
["inventory-connector"]
----
--

. Review the connector's tasks:
+
--
[source,shell,options="nowrap"]
----
$ curl -i -X GET -H "Accept:application/json" localhost:8083/connectors/inventory-connector
----

You should see a response similar to the following (formatted for readability):

[source,json,options="nowrap"]
----
HTTP/1.1 200 OK
Date: Thu, 06 Feb 2020 22:12:03 GMT
Content-Type: application/json
Content-Length: 531
Server: Jetty(9.4.20.v20190813)

{
  "name": "inventory-connector",
  ...
  "tasks": [
    {
      "connector": "inventory-connector",
      "task": 0
    }
  ]
}
----

The connector is running a single task (task `0`) to do its work.
The connector only supports a single task, because MySQL records all of its activities in one sequential `binlog`.
As a result, the connector requires only a single reader to obtain a consistent, ordered view of all of the events.
--
