[id="server-introduction-debezium"]
= Introduction to {prodname} Server

{prodname} is a distributed platform that converts information from your existing databases into event streams, enabling applications to detect, and immediately respond to row-level changes in the databases.

{prodname} provides a ready-to-use application that streams change events from a source database to messaging infrastructure like Amazon Kinesis, Google Cloud Pub/Sub, Apache Pulsar, Redis (Stream), or NATS JetStream. 
For streaming change events to Apache Kafka, it is recommended to xref:kc-tutorial.adoc[deploy the Debezium connectors via Kafka Connect].

Each of the connectors works with a specific database management system (DBMS).
Connectors record the history of data changes in the DBMS by detecting changes as they occur, and streaming a record of each change event to your chosen sink.
Consuming applications can then read the resulting event records.

The tutorial that follows shows you how to deploy and use the {link-prefix}:{link-mysql-connector}#debezium-connector-for-mysql[{prodname} MySQL connector] with a simple configuration.
For more information about deploying and using {prodname} connectors, see the connector documentation.

.Additional resources
ifdef::community[]
* xref:{link-cassandra-connector}#debezium-connector-for-cassandra[{prodname} connector for Cassandra]
endif::community[]
* {link-prefix}:{link-db2-connector}#debezium-connector-for-db2[{prodname} connector for Db2]
* {link-prefix}:{link-mongodb-connector}#debezium-connector-for-mongodb[{prodname} connector for MongoDB]
* {link-prefix}:{link-mysql-connector}#debezium-connector-for-mysql[{prodname} connector for MySQL]
* {link-prefix}:{link-oracle-connector}#debezium-connector-for-oracle[{prodname} connector for Oracle Database]
* {link-prefix}:{link-postgresql-connector}#debezium-connector-for-postgresql[{prodname} connector for PostgreSQL]
* {link-prefix}:{link-sqlserver-connector}#debezium-connector-for-sql-server[{prodname} connector for SQL Server]
ifdef::community[]
* xref:{link-vitess-connector}#debezium-connector-for-vitess[{prodname} connector for Vitess]
endif::community[]
