ALTER TABLE test1 SPLIT PARTITION p_MAXV
    AT (TO_DATE('01/01/2030', 'DD/MM/YYYY'))
    INTO (partition p_2029 TABLESPACE users, partition p_MAXV) ONLINE;

ALTER TABLE fruit ANNOTATIONS (Visibility 'Everyone');

ALTER TABLE fruit ANNOTATIONS (drop Visibility);

ALTER TABLE fruit ANNOTATIONS (add Visibility 'Everyone');

ALTER TABLE fruit MODIFY (id ANNOTATIONS (Visibility 'Hidden'));

ALTER TABLE fruit MODIFY (id ANNOTATIONS (drop Visibility));

ALTER TABLE fruit MODIFY (id ANNOTATIONS (add Visibility 'Hidden'));

ALTER TABLE NAV.SPAC_AUT_APOLICE MODIFY SUBPARTITION P12345 SHRINK SPACE CHECK;

ALTER TABLE test1 DISABLE LOGICAL REPLICATION;

ALTER TABLE test1 ENABLE LOGICAL REPLICATION;
ALTER TABLE test1 ENABLE LOGICAL REPLICATION ALL KEYS;
ALTER TABLE test1 ENABLE LOGICAL REPLICATION ALLOW NOVALIDATE KEYS;
ALTER TABLE test1 ENABLE LOGICAL REPLICATION PARTIAL JSON;
ALTER TABLE test1 ENABLE LOGICAL REPLICATION NO PARTIAL JSON;

ALTER TABLE VIDEO ADD (sql_code_injection_check NUMBER GENERATED ALWAYS AS (sdd_avoid_sql_injection(SKRIPT)) VIRTUAL);
ALTER TABLE VIDEO ADD (sql_code_injection_check NUMBER GENERATED ALWAYS AS (sdd_avoid_sql_injection(SKRIPT)) VIRTUAL BY USER FOR STATISTICS);

ALTER TABLE USR_SAT_ADMCC.ACC_R65_OPERACAO
    MOVE PARTITION P_INICIAL
    COMPRESS FOR QUERY HIGH
    TABLESPACE TBS_SAT_ADMCC_DATA_2005
    UPDATE INDEXES;

ALTER TABLE USR_SAT_ADMCC.ACC_R65_OPERACAO
    MOVE SUBPARTITION SP_INICIAL
    COMPRESS FOR QUERY HIGH
    TABLESPACE TBS_SAT_ADMCC_DATA_2005
    UPDATE INDEXES;