CREATE TABLE deptXTec3
    ORGANIZATION EXTERNAL ( TYPE ORACLE_DATAPUMP DEFAULT DIRECTORY def_dir1
                            ACCESS PARAMETERS (COMPRESSION ENABLED)
                            LOCATION ('dept.dmp'));

CREATE TABLE inv_part_all_xt (PRODUCT_ID NUMBER(6), WAREHOUSE_ID NUMBER(3), QUANTITY_ON_HAND NUMBER(8))
    ORGANIZATION EXTERNAL ( TYPE ORACLE_DATAPUMP DEFAULT DIRECTORY def_dir1
                            ACCESS PARAMETERS (COMPRESSION ENABLED)
                            LOCATION ('inv_p1_xt.dmp','inv_p2_xt.dmp'));

CREATE TABLE emp_load (first_name CHAR(15), last_name CHAR(20), resume CHAR(2000), picture RAW (2000))
    ORGANIZATION EXTERNAL ( TYPE ORACLE_LOADER DEFAULT DIRECTORY ext_tab_dir
                            ACCESS PARAMETERS (FIELDS (first_name VARCHARC(5,12), last_name VARCHARC(2,20), resume VARCHARC(4,10000), picture VARRAWC(4,100000)))
                            LOCATION ('info.dat'));

CREATE TABLE emp_load (first_name CHAR(15), last_name CHAR(20), resume CHAR(2000), picture RAW (2000))
    ORGANIZATION EXTERNAL ( TYPE ORACLE_LOADER DEFAULT DIRECTORY ext_tab_dir
                            ACCESS PARAMETERS ( RECORDS VARIABLE 2 DATA IS BIG ENDIAN CHARACTERSET US7ASCII
                                                FIELDS (first_name VARCHAR(2,12), last_name VARCHAR(2,20), resume VARCHAR(4,10000), picture VARRAW(4,100000)))
                            LOCATION ('info.dat'));

CREATE TABLE emp_load (first_name CHAR(15), last_name CHAR(20), year_of_birth INT, phone CHAR(12), area_code CHAR(3), exchange CHAR(3), extension CHAR(4))
    ORGANIZATION EXTERNAL ( TYPE ORACLE_LOADER DEFAULT DIRECTORY ext_tab_dir
                            ACCESS PARAMETERS ( FIELDS RTRIM (first_name (1:15) CHAR(15), last_name (*:+20), year_of_birth (36:39), phone (40:52), area_code (*-12: +3), exchange (*+1: +3), extension (*+1: +4)))
                            LOCATION ('info.dat'));

CREATE TABLE emp_load (first_name CHAR(15), last_name CHAR(20), year_of_birth CHAR(4))
    ORGANIZATION EXTERNAL ( TYPE ORACLE_LOADER DEFAULT DIRECTORY ext_tab_dir
                            ACCESS PARAMETERS ( FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '(' and ')' LRTRIM )
                            LOCATION ('info.dat'));

CREATE TABLE xtab (recno varchar2(2000))
    ORGANIZATION EXTERNAL ( TYPE ORACLE_LOADER DEFAULT DIRECTORY data_dir
                            ACCESS PARAMETERS ( RECORDS DELIMITED BY NEWLINE
                                                PREPROCESSOR execdir:'zcat'
                                                LOGFILE 'deptxt1.log'
                                                BADFILE 'deptXT.bad'
                                                FIELDS TERMINATED BY ',' MISSING FIELD VALUES ARE NULL (recno char(2000)))
                            LOCATION ('foo.dat.gz')) REJECT LIMIT UNLIMITED;

CREATE TABLE deptxt1 ( deptno number(2), dname varchar2(14), loc varchar2(13))
    ORGANIZATION EXTERNAL ( TYPE ORACLE_LOADER DEFAULT DIRECTORY dpump_dir
                            ACCESS PARAMETERS ( EXTERNAL VARIABLE DATA
                                               LOGFILE 'deptxt1.log'
                                               READSIZE=10000
                                               PREPROCESSOR execdir:'uncompress.sh' )
                            LOCATION ('deptxt1.dmp')) REJECT LIMIT UNLIMITED;

CREATE TABLE "T_XT" ("C0" VARCHAR2(2000))
    ORGANIZATION EXTERNAL ( TYPE ORACLE_LOADER DEFAULT DIRECTORY DMPDIR
                            ACCESS PARAMETERS ( RECORDS XMLTAG ("home address", "work address", "home phone")
                                                READSIZE 1024
                                                SKIP 0
                                                FIELDS NOTRIM MISSING FIELD VALUES ARE NULL)
                            LOCATION ('t.dat')) REJECT LIMIT UNLIMITED;

CREATE TABLE emp_load (first_name CHAR(15), last_name CHAR(20), year_of_birth CHAR(4))
    ORGANIZATION EXTERNAL ( TYPE ORACLE_LOADER DEFAULT DIRECTORY ext_tab_dir
                            ACCESS PARAMETERS ( RECORDS DELIMITED BY '|' FIELDS TERMINATED BY ','
                                              ( first_name CHAR(7), last_name CHAR(8), year_of_birth CHAR(4)))
                            LOCATION ('info.dat'));

CREATE TABLE emp_load (first_name CHAR(15), last_name CHAR(20), year_of_birth CHAR(4))
    ORGANIZATION EXTERNAL ( TYPE ORACLE_LOADER DEFAULT DIRECTORY ext_tab_dir
                            ACCESS PARAMETERS (RECORDS FIXED 20 FIELDS (first_name CHAR(7), last_name CHAR(8), year_of_birth CHAR(4)))
                            LOCATION ('info.dat'));

CREATE TABLE CUSTOMER_TABLE (cust_num VARCHAR2(10), order_num VARCHAR2(20), order_date DATE, item_cnt NUMBER, description VARCHAR2(100), order_total NUMBER(8,2))
    ORGANIZATION EXTERNAL ( TYPE ORACLE_HIVE
                            ACCESS PARAMETERS (
                                com.oracle.bigdata.tableName:  order_db.order_summary
                                com.oracle.bigdata.colMap:     {"col":"ITEM_CNT", "field":"order_line_item_count"}
                                com.oracle.bigdata.overflow:   {"action":"ERROR", "col":"DESCRIPTION"}
                                com.oracle.bigdata.errorOpt:   [{"action":"replace", "value":"INV_NUM" , "col":["CUST_NUM","ORDER_NUM"]} , {"action":"reject", "col":"ORDER_TOTAL"}]
                          ));

CREATE TABLE "MASTERBILL"."ET$03D5D0AD0001" ("USER#", "NAME")
    ORGANIZATION EXTERNAL (
        TYPE ORACLE_DATAPUMP
        DEFAULT DIRECTORY "DBEXPORT"
        ACCESS PARAMETERS (
            DEBUG = (0 , 0)
            DATAPUMP INTERNAL TABLE "SYS"."KU$_USER_MAPPING_VIEW"
            TEMPLATE_TABLE "KU$_USER_MAPPING_VIEW_TBL"
            JOB ( "MASTERBILL","SYS_EXPORT_FULL_01",2)
            WORKERID 1
            PARALLEL 1
            VERSION '19.3.0.0.0'
            ENCRYPTPASSWORDISNULL
            COMPRESSION DISABLED
            ENCRYPTION DISABLED )
        LOCATION ('bogus.dat')
    )
    PARALLEL 1
    REJECT LIMIT UNLIMITED
    AS SELECT X FROM "SYS"."KU$_USER_MAPPING_VIEW" KU$;

CREATE TABLE fruit (
    id NUMERIC(9,0) PRIMARY KEY ANNOTATIONS (Visibility 'Everyone'));

CREATE TABLE fruit (
    id NUMERIC(9,0) PRIMARY KEY,
    data varchar2(50))
    ANNOTATIONS (Visibility 'Everyone');

CREATE TABLE T$BO_PATIENT_LMAP NOLOGGING TABLESPACE CMX_TEMP_TDE PARALLEL 2 INSTANCES 2 AS
    SELECT DISTINCT XREF.ORIG_ROWID_OBJECT, XREF.ROWID_OBJECT
      FROM C_S_PATIENT STAGE INNER JOIN C_BO_PATIENT_XREF XREF ON XREF.ORIG_ROWID_OBJECT = STAGE.ROWID_OBJECT
     WHERE STAGE.ROWID_OBJECT IS NOT NULL;

CREATE TABLE T$BO_PATIENT_LMAP NOLOGGING TABLESPACE CMX_TEMP_TDE PARALLEL (DEGREE 1) AS
    SELECT DISTINCT XREF.ORIG_ROWID_OBJECT, XREF.ROWID_OBJECT
      FROM C_S_PATIENT STAGE INNER JOIN C_BO_PATIENT_XREF XREF ON XREF.ORIG_ROWID_OBJECT = STAGE.ROWID_OBJECT
     WHERE STAGE.ROWID_OBJECT IS NOT NULL;

CREATE TABLE T$BO_PATIENT_LMAP NOLOGGING TABLESPACE CMX_TEMP_TDE PARALLEL (DEGREE 1 INSTANCES 2) AS
    SELECT DISTINCT XREF.ORIG_ROWID_OBJECT, XREF.ROWID_OBJECT
      FROM C_S_PATIENT STAGE INNER JOIN C_BO_PATIENT_XREF XREF ON XREF.ORIG_ROWID_OBJECT = STAGE.ROWID_OBJECT
     WHERE STAGE.ROWID_OBJECT IS NOT NULL;

CREATE TABLE "ESPP"."T_BUSINESS_OPERATION" (
    "BO_ID" NUMBER(38,0) NOT NULL ENABLE,
	"BO_TYPE" NUMBER(6,0) NOT NULL ENABLE,
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS,
	 CONSTRAINT "T_BO_TYPE_FK" FOREIGN KEY ("BO_TYPE")
	  REFERENCES "ESPP"."TD_OPERATION_TYPE" ("OT_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  STORAGE (
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ESPP"
  PARTITION BY REFERENCE ("T_BO_TR_FK")
  (PARTITION "SYS_P1329" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  NOCOMPRESS LOGGING
  STORAGE (
  INITIAL 134217728 NEXT 134217728 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ESPP",
  PARTITION "SYS_P1330" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  NOCOMPRESS LOGGING);

CREATE TABLE "TBG"."SCS_DM_DOCUMENTS"(
    "BRANCH" VARCHAR2(8 CHAR) NOT NULL ENABLE,
    "NO" NUMBER(30,0) NOT NULL ENABLE,
    "DOC_TYPE" VARCHAR2(7 CHAR) NOT NULL ENABLE,
    "ID" VARCHAR2(32 CHAR),
    CONSTRAINT "SCS_DM_DOCUMENTS_PK" PRIMARY KEY ("NO", "BRANCH") USING INDEX ENABLE)
    INMEMORY PRIORITY LOW NO MEMCOMPRESS
    DISTRIBUTE AUTO NO DUPLICATE
    PARTITION BY LIST ("PARTITION_KEY")
    SUBPARTITION BY HASH ("NO")
    SUBPARTITIONS 1
    (PARTITION "SCS_DM_DOCUMENTS_NEW"
        VALUES (64001) INMEMORY PRIORITY LOW NO MEMCOMPRESS DISTRIBUTE AUTO NO DUPLICATE
        ( SUBPARTITION "SYS_SUBP301" INMEMORY PRIORITY LOW NO MEMCOMPRESS DISTRIBUTE AUTO NO DUPLICATE ) ,
     PARTITION "SCS_DM_DOCUMENTS_ARC"
        VALUES (0) INMEMORY PRIORITY LOW NO MEMCOMPRESS DISTRIBUTE AUTO NO DUPLICATE
        ( SUBPARTITION "SYS_SUBP302" INMEMORY PRIORITY LOW NO MEMCOMPRESS DISTRIBUTE AUTO NO DUPLICATE ) ) ;

CREATE TABLE "ORACDC"."DEPARTMENT"  (
    "EMP_NO" VARCHAR2(20) NOT NULL ENABLE,
    "REQUEST_ID" VARCHAR2(30) NOT NULL ENABLE,
    SUPPLEMENTAL LOG GROUP "GGS_19282" ("EMP_NO", "REQUEST_ID") ALWAYS,
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS,
    CONSTRAINT "DEPARTMENT_FK" FOREIGN KEY ("EMP_NO")
        REFERENCES "ORACDC"."MEM_REG" ("EMP_NO") ENABLE NOVALIDATE)
    PARTITION BY HASH ("EMP_NO") (
        PARTITION "DEPARTMENT_P1",
        PARTITION "DEPARTMENT_P2",
        PARTITION "DEPARTMENT_P32" );

CREATE TABLE "ZZZ"."TASKVOLUME" (
    "TASK" NUMBER,
    "SUBJECT" NUMBER NOT NULL ENABLE,
    "VOL" NUMBER,
    "START_TIME" DATE,
    "END_TIME" DATE,
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS,
    SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS,
    SUPPLEMENTAL LOG DATA (UNIQUE INDEX) COLUMNS,
    SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS);

CREATE TABLE "SCHEMA"."TYPE_GEOMETRY" (
    "ID" NUMBER(9,0) NOT NULL ENABLE,
    "LOCATION" SDO_GEOMETRY,
    PRIMARY KEY ("ID") USING INDEX ENABLE,
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS )
    VARRAY "LOCATION"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB
    VARRAY "LOCATION"."SDO_ORDINATES" STORE AS SECUREFILE LOB;

CREATE TABLE "SCHEMA"."TYPE_GEOMETRY" (
    "ID" NUMBER(9,0) NOT NULL ENABLE,
    "LOCATION" "SDO_GEOMETRY",
    PRIMARY KEY ("ID") USING INDEX ENABLE);

CREATE TABLE "MYUSER"."ITEMS" (
    "ID" NUMBER(4,0) GENERATED BY DEFAULT ON NULL AS IDENTITY
        MINVALUE 1
        MAXVALUE 9999999999999999999999999999
        INCREMENT BY 1
        START WITH 101
        CACHE 20
        NOORDER
        NOCYCLE
        NOKEEP
        NOSCALE NOT NULL ENABLE,
    "NAME" VARCHAR2(255) NOT NULL ENABLE,
    PRIMARY KEY ("ID") USING INDEX ENABLE,
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS);

CREATE TABLE "ET$xxxx"
   (    "MANDT",
    "WERKS",
    "MATNR",
    "GZEQUNR",
    "GZEQUNED",
    "MODNE",
    "NAME1",
    "MAKTX"
   ) ORGANIZATION EXTERNAL
    ( TYPE ORACLE_DATAPUMP DEFAULT DIRECTORY "DMPDP"
        ACCESS PARAMETERS (
            DEBUG = (0 , 0) DATAPUMP INTERNAL TABLE "xxxx"."xxxx"
            JOB ("GGS","SYS_EXPORT_TABLE_01",1)
            WORKERID 1
            PARALLEL 1
            VERSION '11.2.0.0.0'
            ENCRYPTPASSWORDISNULL COMPRESSION ENABLED ENCRYPTION DISABLED  DBLINK 'TOPRD')
        LOCATION ('xxxx.dat') )
        PARALLEL 1 REJECT LIMIT UNLIMITED
    AS SELECT /*+ PARALLEL(KU$,1) */ "MANDT", "WERKS", "MATNR", "GZEQUNR", "GZEQUNED", "MODNE", "NAME1", "MAKTX"
    FROM RELATIONAL("xxxx"."xxxx" @TOPRD NOT XMLTYPE) AS OF SCN 216399751091 KU$;

CREATE TABLE "ZZZ"."TASKVOLUME" (
    "TASK" NUMBER,
    "SUBJECT" NUMBER NOT NULL ENABLE,
    "VOL" NUMBER,
    "START_TIME" DATE,
    "END_TIME" DATE)
    PARTITION BY RANGE ("TASK")
    SUBPARTITION BY LIST ("VOL")
    (PARTITION "VOL_0"  VALUES LESS THAN (1) (
        SUBPARTITION "VOL_0_R"  VALUES (-1),
        SUBPARTITION "VOL_0_01"  VALUES (01),
        SUBPARTITION "VOL_0_02"  VALUES (02),
        SUBPARTITION "VOL_0_03"  VALUES (03),
        SUBPARTITION "VOL_0_04"  VALUES (04)));

CREATE TABLE character_varying_table (
    data0 character,
    data1 character(5),
    data2 character varying(5));

CREATE TABLE "SCHEMA"."TYPE_GEOMETRY" (
    "ID" NUMBER(9,0) NOT NULL ENABLE,
    "LOCATION" SDO_GEOMETRY,
    PRIMARY KEY ("ID") USING INDEX ENABLE);

CREATE TABLE "ETUDES"."IMPORT_EXMETI" (
    abort_step NUMBER,
    access_method VARCHAR2(16),
    template_table VARCHAR2(128),
    timezone VARCHAR2(64))
    SEGMENT CREATION IMMEDIATE NO INMEMORY INITRANS 100;
