CREATE MATERIALIZED VIEW LOG ON MY_SCHEMA.MY_TABLE;

CREATE MATERIALIZED VIEW LOG ON MY_SCHEMA.MY_TABLE WITH PRIMARY KEY INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON MY_SCHEMA.MY_TABLE WITH ROWID, SEQUENCE (ID, NAME) INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON MY_SCHEMA.MY_TABLE WITH PRIMARY KEY, ROWID (ID) EXCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON MY_SCHEMA.MY_TABLE WITH COMMIT SCN;

CREATE MATERIALIZED VIEW LOG ON MY_SCHEMA.MY_TABLE WITH OBJECT ID;

CREATE MATERIALIZED VIEW LOG ON MY_SCHEMA.MY_TABLE WITH ROWID PURGE IMMEDIATE ASYNCHRONOUS;

CREATE MATERIALIZED VIEW LOG ON MY_SCHEMA.MY_TABLE WITH ROWID INCLUDING NEW VALUES PURGE IMMEDIATE SYNCHRONOUS;

CREATE MATERIALIZED VIEW LOG ON MY_SCHEMA.MY_TABLE
    PCTFREE 5
    TABLESPACE USERS
    CACHE
    NOLOGGING
    PARALLEL 4
    WITH PRIMARY KEY, ROWID;

CREATE MATERIALIZED VIEW LOG ON MY_SCHEMA.MY_TABLE
    TABLESPACE MVIEWLOG
    NOCACHE
    LOGGING
    NOPARALLEL
    WITH ROWID
    EXCLUDING NEW VALUES;
