DROP TABLE employee;
DROP TABLE employee PURGE;
DROP TABLE employee IF EXISTS;
DROP TABLE TEST.TAB FORCE;
DROP TABLE TEST.STUDENT CASCADE CONSTRAINTS;
DROP TABLE TEST.STUDENT IF EXISTS CASCADE CONSTRAINTS;
DROP TABLE STTRANS240302 CASCADE CONSTRAINT AS 'BIN$ODxFbg8pH9TgYwo6AVpSRg==$0';
DROP TABLE inbox CASCADE CONSTRAINT AS "BIN$yv+1ra/roTjgUwEBAH+ByQ==$0" ;