truncate table test;

TRUNCATE TABLE test PRESERVE;

TRUNCATE TABLE test PURGE;

TRUNCATE TABLE test DROP STORAGE;

TRUNCATE TABLE test DROP ALL STORAGE;

TRUNCATE TABLE test REUSE STORAGE;

TRUNCATE TABLE test CASCADE;

