CREATE TABLE "SCHEMA1"."TABLE1"
(
    "COL1" "SYS"."XMLTYPE"
) XMLTYPE COLUMN "COL1" STORE AS BASICFILE BINARY XML "TABLE1_COL1_SEG"(ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  CACHE READS LOGGING ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA;

CREATE TABLE T (X CLOB)
    LOB ("X") STORE AS SECUREFILE "X_SEG"
        (ENABLE STORAGE IN ROW 32000 CHUNK 8192 NOCACHE LOGGING);

CREATE TABLE T (X XMLTYPE)
    XMLTYPE COLUMN "X" STORE AS BASICFILE BINARY XML "X_SEG"
        (ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION CACHE READS LOGGING) ALLOW NONSCHEMA DISALLOW ANYSCHEMA;

CREATE TABLE T (X XMLTYPE) XMLTYPE COLUMN "X" STORE AS BINARY XML ALLOW ANYSCHEMA ALLOW NONSCHEMA;

CREATE TABLE T (X XMLTYPE) XMLTYPE COLUMN "X" STORE AS BINARY XML ELEMENT PurchaseOrder;
