version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_DELETE_TOPIC_ENABLE=true
  postgres:
    image: quay.io/debezium/example-postgres:${DEBEZIUM_VERSION}
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    links:
     - kafka
     - postgres
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=tpc_connect_configs
     - OFFSET_STORAGE_TOPIC=tpc_connect_offsets
     - STATUS_STORAGE_TOPIC=tpc_connect_statuses
  tpc:
    image: debezium-tpc
    build:
      context: .
    privileged: True
    links:
      - kafka
      - postgres
      - connect
    volumes: 
      - ../../debezium-examples/tutorial/register-postgres.json:/home/tpc/register.json
      - ${DEBEZIUM_TPC_VOLUME}:/home/tpc/tpcdata
