ALTER SESSION
    SET QUERY_REWRITE_ENABLED = TRUE;

ALTER SESSION
    SET NLS_SORT = XSpanish;

ALTER SESSION
    SET NLS_LANGUAGE = FRENCH;

ALTER SESSION SET NLS_CURRENCY = 'FF';

ALTER SESSION
    ADVISE COMMIT;

ALTER SESSION ENABLE PARALLEL DML;
