ALTER DISKGROUP hmdg ADD FILEGROUP fgtem TEMPLATE SET 'datafile.redundancy'='unprotected';

ALTER DISKGROUP hmdg ADD FILEGROUP fgdb DATABASE NONE FROM TEMPLATE fgtem;

ALTER DISKGROUP hmdg ADD FILEGROUP fgtem2 TEMPLATE FROM TEMPLATE fgtem;

ALTER DISKGROUP dgroup_01
  ADD DISK '/devices/disks/d100';

ALTER DISKGROUP dgroup_01
  DROP DISK dgroup_01_0000;

ALTER DISKGROUP dgroup_01
UNDROP DISKS;

ALTER DISKGROUP dgroup_01
  RESIZE ALL
  SIZE 36G;

ALTER DISKGROUP dgroup_01
  REBALANCE POWER 11 WAIT;

ALTER DISKGROUP dgroup_01
  CHECK ALL
  REPAIR;

ALTER DISKGROUP dgroup_01
  ADD TEMPLATE template_01
    ATTRIBUTES (UNPROTECTED COARSE);

ALTER DISKGROUP dgroup_01
  MODIFY TEMPLATE template_01
    ATTRIBUTES (FINE);

ALTER DISKGROUP dgroup_01
  DROP TEMPLATE template_01;

ALTER DISKGROUP dgroup_01
  ADD DIRECTORY '+dgroup_01/alias_dir';

ALTER DISKGROUP dgroup_01
  ADD ALIAS '+dgroup_01/alias_dir/datafile.dbf'
    FOR '+dgroup_01.261.1';

ALTER DISKGROUP dgroup_01
  SCRUB REPAIR WAIT;

ALTER DISKGROUP dgroup_01
  DISMOUNT FORCE;

ALTER DISKGROUP dgroup_01
  MOUNT;
