ALTER TABLESPACE tbs_01 
    BEGIN BACKUP; 
ALTER TABLESPACE tbs_01
   END BACKUP;

ALTER TABLESPACE tbs_02 OFFLINE NORMAL;

ALTER TABLESPACE tbs_02
  RENAME DATAFILE 'diskb:tbs_f5.dbf'
  TO              'diska:tbs_f5.dbf';

ALTER TABLESPACE tbs_02 ONLINE;

ALTER TABLESPACE tbs_03
    ADD DATAFILE 'tbs_f04.dbf'
    SIZE 100K
    AUTOEXTEND ON
    NEXT 10K
    MAXSIZE 100K;

ALTER TABLESPACE tbs_03
    DROP DATAFILE 'tbs_f04.dbf';

ALTER TABLESPACE temp_demo ADD TEMPFILE 'temp05.dbf' SIZE 5 AUTOEXTEND ON;

ALTER TABLESPACE temp_demo DROP TEMPFILE 'temp05.dbf';

ALTER TABLESPACE temp_demo SHRINK SPACE;

ALTER TABLESPACE omf_ts1 ADD DATAFILE;

ALTER TABLESPACE tbs_03 NOLOGGING;
ALTER TABLESPACE undots1
  RETENTION NOGUARANTEE;
ALTER TABLESPACE undots1
  RETENTION GUARANTEE;
