alter role TEST_ROLE_AAA NOT IDENTIFIED;

alter role TEST_ROLE_AAA  IDENTIFIED BY data;

alter role TEST_ROLE_AAA  IDENTIFIED EXTERNALLY;

ALTER ROLE TEST_ROLE_AAA IDENTIFIED USING hr.admin;

alter role TEST_ROLE_AAA  IDENTIFIED GLOBALLY;


ALTER ROLE dw_manager IDENTIFIED GLOBALLY AS 'domain_name_of_directory_group' ;
ALTER ROLE warehouse_user NOT IDENTIFIED CONTAINER = CURRENT;
ALTER ROLE warehouse_user NOT IDENTIFIED CONTAINER = ALL;
