ALTER DATABASE testdb 
   DATAFILE '+dgroup_01/testdb/datafile/system.261.1' ONLINE;
ALTER DATABASE OPEN READ ONLY;
ALTER DATABASE
   RECOVER TABLESPACE tbs_03
   PARALLEL;
ALTER DATABASE
  ADD LOGFILE GROUP 3 
    ('diska:log3.log' ,  
     'diskb:log3.log') SIZE 50K; 
ALTER DATABASE  
    ADD LOGFILE THREAD 5 GROUP 4  
        ('diska:log4.log', 
         'diskb:log4:log'); 
ALTER DATABASE   
   ADD LOGFILE MEMBER 'diskc:log3.log'  
   TO GROUP 3; 
ALTER DATABASE
    DROP LOGFILE MEMBER 'diskb:log3.log'; 
ALTER DATABASE DROP LOGFILE GROUP 3;
ALTER DATABASE   
    RENAME FILE 'diskc:log3.log' TO 'diskb:log3.log'; 
ALTER DATABASE
    SET DEFAULT BIGFILE TABLESPACE;
ALTER DATABASE 
   DEFAULT TEMPORARY TABLESPACE tbs_05;
ALTER DATABASE TEMPFILE 'temp02.dbf' OFFLINE;
ALTER DATABASE RENAME FILE 'temp02.dbf' TO 'temp03.dbf';
ALTER DATABASE  
    RENAME GLOBAL_NAME TO demo.world.oracle.com; 
ALTER DATABASE
  ENABLE BLOCK CHANGE TRACKING
    USING FILE 'tracking_file' REUSE;
ALTER DATABASE
  DISABLE BLOCK CHANGE TRACKING;
ALTER DATABASE  
    DATAFILE 'diskb:tbs_f5.dat' RESIZE 10 M;
ALTER DATABASE  
    CLEAR LOGFILE 'diskc:log3.log';
ALTER DATABASE 
  RECOVER AUTOMATIC DATABASE;
ALTER DATABASE 
    RECOVER LOGFILE 'diskc:log3.log'; 
--TODO: fix grammar
--ALTER DATABASE  
--   RECOVER STANDBY DATAFILE '/finance/stbs_21.f' 
--   UNTIL CONTROLFILE;
ALTER DATABASE 
   RECOVER MANAGED STANDBY DATABASE;
