ALTER MATERIALIZED VIEW sales_by_month_by_state
   REFRESH FAST; 

ALTER MATERIALIZED VIEW sales_by_month_by_state
   REFRESH NEXT SYSDATE+7;
ALTER MATERIALIZED VIEW sales_by_month_by_state CONSIDER FRESH;

ALTER MATERIALIZED VIEW emp_data
   REFRESH COMPLETE
   START WITH TRUNC(SYSDATE+1) + 9/24
   NEXT SYSDATE+7;
ALTER MATERIALIZED VIEW emp_data
   ENABLE QUERY REWRITE;
ALTER MATERIALIZED VIEW order_data
   REFRESH WITH PRIMARY KEY;
ALTER MATERIALIZED VIEW order_data COMPILE;
