-- inmemory_table_clause
ALTER TABLE customer INMEMORY;

ALTER TABLE customer NO INMEMORY;

-- inmemory_memcompress
ALTER TABLE customer INMEMORY MEMCOMPRESS FOR DML;

ALTER TABLE customer INMEMORY MEMCOMPRESS FOR QUERY;
ALTER TABLE customer INMEMORY MEMCOMPRESS FOR QUERY LOW;
ALTER TABLE customer INMEMORY MEMCOMPRESS FOR QUERY HIGH;

ALTER TABLE customer INMEMORY MEMCOMPRESS FOR CAPACITY;
ALTER TABLE customer INMEMORY MEMCOMPRESS FOR CAPACITY LOW;
ALTER TABLE customer INMEMORY MEMCOMPRESS FOR CAPACITY HIGH;

ALTER TABLE customer INMEMORY NO MEMCOMPRESS;

-- inmemory_priority
ALTER TABLE customer INMEMORY PRIORITY NONE;
ALTER TABLE customer INMEMORY PRIORITY LOW;
ALTER TABLE customer INMEMORY PRIORITY MEDIUM;
ALTER TABLE customer INMEMORY PRIORITY HIGH;
ALTER TABLE customer INMEMORY PRIORITY CRITICAL;

-- inmemory_distribute
ALTER TABLE customer INMEMORY DISTRIBUTE;
ALTER TABLE customer INMEMORY DISTRIBUTE AUTO;
ALTER TABLE customer INMEMORY DISTRIBUTE BY ROWID RANGE;
ALTER TABLE customer INMEMORY DISTRIBUTE BY PARTITION;
ALTER TABLE customer INMEMORY DISTRIBUTE BY SUBPARTITION;

ALTER TABLE customer INMEMORY DISTRIBUTE FOR SERVICE DEFAULT;
ALTER TABLE customer INMEMORY DISTRIBUTE FOR SERVICE ALL;
ALTER TABLE customer INMEMORY DISTRIBUTE FOR SERVICE some_service;
ALTER TABLE customer INMEMORY DISTRIBUTE FOR SERVICE NONE;

ALTER TABLE customer INMEMORY DISTRIBUTE BY ROWID RANGE FOR SERVICE DEFAULT;

-- inmemory_duplicate
ALTER TABLE customer INMEMORY DUPLICATE;
ALTER TABLE customer INMEMORY DUPLICATE ALL;
ALTER TABLE customer INMEMORY NO DUPLICATE;

-- inmemory_column_clause
ALTER TABLE customer INMEMORY INMEMORY (customer_name);
ALTER TABLE customer INMEMORY (customer_name, customer_id);
ALTER TABLE customer INMEMORY (name) INMEMORY (customer_id);
ALTER TABLE customer INMEMORY (name) NO INMEMORY (customer_id);
ALTER TABLE customer INMEMORY MEMCOMPRESS FOR QUERY LOW (name) NO INMEMORY (customer_id);

-- verify usage of ... as regular id
CREATE TABLE vendor (SERVICE VARCHAR2(100));
