ANALYZE TABLE orders DELETE STATISTICS;
ANALYZE INDEX inv_product_ix VALIDATE STRUCTURE;
ANALYZE TABLE employees VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE customers VALIDATE REF UPDATE;
ANALYZE TABLE customers VALIDATE STRUCTURE ONLINE;
ANALYZE CLUSTER personnel
    VALIDATE STRUCTURE CASCADE;
ANALYZE TABLE orders
   LIST CHAINED ROWS INTO chained_rows;
