AUDIT ROLE; 
AUDIT ROLE
    WHENEVER SUCCESSFUL;
AUDIT ROLE
    WHENEVER NOT SUCCESSFUL;
AUDIT SELECT TABLE, UPDATE TABLE;
AUDIT SELECT TABLE, UPDATE TABLE
    BY hr, oe;
AUDIT DELETE ANY TABLE;
AUDIT CREATE ANY DIRECTORY;
AUDIT DIRECTORY;
AUDIT READ ON DIRECTORY bfile_dir;
AUDIT SELECT
    ON hr.employees;
AUDIT SELECT
    ON hr.employees
    WHENEVER SUCCESSFUL;
AUDIT SELECT
    ON hr.employees
    WHENEVER NOT SUCCESSFUL;
AUDIT INSERT, UPDATE
    ON oe.customers;
AUDIT ALL
    ON hr.employees_seq;
AUDIT ALTER, GRANT, INSERT, UPDATE, DELETE
    ON DEFAULT;

