create role TEST_ROLE_AAA ;

create role TEST_ROLE_BBB  NOT IDENTIFIED ;

create role TEST_ROLE_CCC IDENTIFIED BY TEST_ROLE_AAA;

create role TEST_ROLE_DDD  IDENTIFIED EXTERNALLY;

create role TEST_ROLE_EEE IDENTIFIED GLOBALLY;


