CREATE PUBLIC DATABASE LINK remote USING 'remote';
CREATE DATABASE LINK local CONNECT TO hr IDENTIFIED BY p4ssword USING 'local';
CREATE DATABASE LINK remote.us.example.com CONNECT TO CURRENT_USER USING 'remote';
CREATE DATABASE LINK "LINK" CONNECT TO "DBLINK" IDENTIFIED BY VALUES ':1' USING 'local';

ALTER DATABASE LINK private_link CONNECT TO hr IDENTIFIED BY hr_new_password;
ALTER PUBLIC DATABASE LINK public_link CONNECT TO scott IDENTIFIED BY scott_new_password;
ALTER SHARED PUBLIC DATABASE LINK shared_pub_link CONNECT TO scott IDENTIFIED BY scott_new_password AUTHENTICATED BY hr IDENTIFIED BY hr_new_password;

DROP PUBLIC DATABASE LINK remote;
DROP DATABASE LINK private_link_name;
