-- Test for ignoring the order of DETERMINISTIC and PIPELINED keywords in function bodies
CREATE OR REPLACE PACKAGE BODY TEST AS
    FUNCTION TEST_FUNC RETURN NUMBER PIPELINED DETERMINISTIC AS
    BEGIN
        RETURN NULL;
    END TEST_FUNC;
    
    FUNCTION TEST_FUNC2 RETURN NUMBER DETERMINISTIC PIPELINED AS
    BEGIN
        RETURN NULL;
    END TEST_FUNC2;
END TEST;
