WHENEVER SQLERROR CONTINUE;
WHENEVER SQLERROR CONTINUE COMMIT;
WHENEVER SQLERROR CONTINUE ROLLBACK;
WHENEVER SQLERROR CONTINUE NONE;

WHENEVER SQLERROR EXIT SQL.SQLCODE;
WHENEVER SQLERROR EXIT SQL.SQLCODE COMMIT;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

WHENEVER SQLERROR EXIT 1;
