name: "Build PostgreSQL"
description: "Builds the Debezium PostgreSQL connector"

inputs:
  maven-cache-key:
    description: "The maven build cache key"
    required: true
  profile:
    description: "The PostgreSQL build profile to use"
    required: false
    default: "assembly"
  shell:
    description: "The shell to use"
    required: false
    default: bash

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-java

    - uses: ./.github/actions/maven-cache
      with:
        key: ${{ inputs.maven-cache-key }}

    # Remove skipITs/skipTests
    - name: Build PostgreSQL connector (PostgreSQL - ${{ inputs.profile }})
      shell: ${{ inputs.shell }}
      run: >
        ./mvnw clean install -B -pl debezium-connector-postgres -am
        -P${{ inputs.profile }}
        -Ddebezium.test.records.waittime=5
        -Dcheckstyle.skip=true
        -Dformat.skip=true
        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        -Dmaven.wagon.http.pool=false
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
        -DfailFlakyTests=false
        -DskipITs=true
        -DskipTests=true
