/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.redis.clients.jedis)
    api(libs.io.smallrye.reactive.mutiny)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.mockito.mockito.core.x1)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.x1)
    testImplementation(libs.org.testcontainers.testcontainers.x2)
    testImplementation(libs.org.testcontainers.junit.jupiter)
    providedCompile(project(":debezium-api"))
    providedCompile(project(":debezium-core"))
    compileOnly(libs.org.slf4j.slf4j.api.x1)
    compileOnly(libs.org.apache.kafka.connect.api)
    compileOnly(libs.org.apache.kafka.connect.runtime)
}

description = "Debezium Storage Redis Module"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
