To initiate an incremental snapshot, you can send an {link-prefix}:{link-signalling}#debezium-signaling-ad-hoc-incremental-snapshots[ad hoc snapshot signal] to the signaling {data-collection} on the source database.
You submit snapshot signals as SQL `INSERT` queries.

After {prodname} detects the change in the signaling {data-collection}, it reads the signal, and runs the requested snapshot operation.

The query that you submit specifies the {data-collection}s to include in the snapshot, and, optionally, specifies the type of snapshot operation.
{prodname} currently supports the `incremental` and `blocking` snapshot types.

To specify the {data-collection}s to include in the snapshot, provide a `data-collections` array that lists the {data-collection}s, or an array of regular expressions used to match {data-collection}s, for example, +

`{"data-collections": ["public.MyFirstTable", "public.MySecondTable"]}`

Data collection names are case-sensitive.
The `data-collections` array for an incremental snapshot signal has no default value.
If the `data-collections` array is empty, {prodname} interprets the empty array to mean that no action is required, and it does not perform a snapshot.

include::{snippetsdir}/{context}-frag-signaling-fq-table-formats.adoc[leveloffset=+1,tags=fq-table-name-format-note]

.Prerequisites

* {link-prefix}:{link-signalling}#debezium-signaling-enabling-source-signaling-channel[Signaling is enabled].
** A signaling data collection exists on the source database.
** The signaling data collection is specified in the xref:{context}-property-signal-data-collection[`signal.data.collection`] property.

.Using a source signaling channel to trigger an incremental snapshot

. Send a SQL query to add the ad hoc incremental snapshot request to the signaling {data-collection}:
+
[source,sql,indent=0,subs="+attributes,+quotes"]
----
INSERT INTO _<signalTable>_ (id, type, data) VALUES (_'<id>'_, _'<snapshotType>'_, '{"data-collections": ["_<fullyQualfiedTableName>_","_<fullyQualfiedTableName>_"],"type":"_<snapshotType>_","additional-conditions":[{"data-collection": "_<fullyQualfiedTableName>_", "filter": "_<additional-condition>_"}]}');
----
+
For example,
+
include::{snippetsdir}/{context}-frag-signaling-fq-table-formats.adoc[leveloffset=+1,tags=snapshot-signal-example]

+
The values of the `id`,`type`, and `data` parameters in the command correspond to the {link-prefix}:{link-signalling}#debezium-signaling-description-of-required-structure-of-a-signaling-data-collection[fields of the signaling {data-collection}].
The following list describes the parameters in the preceding example:

`INSERT INTO {collection-container}.debezium_signal`::
Specifies the fully-qualified name of the signaling {data-collection} on the source database.

`values`::
`id`:::
The `id` parameter contains the value `ad-hoc`, an arbitrary string that serves as the `id` identifier for the signal request.

`type`:::
The `type` parameter specifies the type of operation to perform, in this case, `execute-snapshot`.

`data`::: The the `data` field of a signal contains the following fields:

`data-collections`:::: An array of {data-collection} names or regular expressions to match {data-collection} names to include in the snapshot.
`type`:::: An optional `type` component of the `data` field of a signal that specifies the type of snapshot operation to run.
+
Valid values are `incremental` and `blocking`.
+
If you do not specify a value, the connector defaults to performing an incremental snapshot.
`additional-conditions`::::
An optional array that specifies a set of additional conditions that the connector evaluates to determine the subset of records to include in a snapshot.
Each additional condition in the array is an object with `data-collection` and `filter` properties.
+
Each `data-collection` in the `additional-conditions` array is specified by its fully-qualified name.
You can specify one or more data collections.
Each collection can be paired with an optional `filter` parameter.
You can pair a unique filter with each data collection.
The value of a `filter` property consists a column label and a value.
When the snapshot runs, for each collection that is named in the array, it captures only the rows that contain the specified filter criteria.
+
In the example, for the `table1` data collection, the signal results in a snapshot that captures only the rows that include the field `color` where the field value is `'blue'`.
+
For more information about the `additional-conditions` parameter, see xref:{context}-incremental-snapshots-additional-conditions[].
