[source,yaml,subs="+attributes"]
----
    apiVersion: {KafkaConnectApiVersion}
    kind: KafkaConnector
    metadata:
      labels:
        strimzi.io/cluster: debezium-kafka-connect-cluster
      name: inventory-connector-{context}
    spec:
      class: io.debezium.connector.{context}.{connector-class}Connector
      tasksMax: 1
      config:
        schema.history.internal.kafka.bootstrap.servers: debezium-kafka-cluster-kafka-bootstrap.debezium.svc.cluster.local:9092
        schema.history.internal.kafka.topic: schema-changes.inventory
        database.hostname: {context}.debezium-{context}.svc.cluster.local
        database.port: {database-port}
        database.user: debezium
        database.password: dbz
        topic.prefix: inventory-connector-{context}
        table.include.list: {include-list-example}

        ...
----
=====================================================================

The following list describes the purpose of select lines in the preceding Kafka connector configuration:

`metadata.name`::
Specifies the name by which the connector is registered with the Kafka Connect cluster.

`spec.class`::
The complete path to the Java class that implements the connector interface.

`spec.tasksMax`::
The maximum number of connector tasks that can operate concurrently.

`spec.config:`::
The connector’s configuration.

`.database.hostname`::
The address of the host database instance.

`.database.port`::
The port number of the database instance.

`.database.user`::
The name of the account that {prodname} uses to connect to the database.

`.database.password`::
The password that {prodname} uses to connect to the database user account.

`.database.server.id`::
Unique numeric ID of the connector.

`.topic.prefix`::
The topic prefix for the database instance or cluster.
The specified name must be formed only from alphanumeric characters or underscores.
Because the topic prefix is used as the prefix for any Kafka topics that receive change events from this connector, the name must be unique among the connectors in the cluster.
This namespace is also used in the names of related Kafka Connect schemas, and the namespaces of a corresponding Avro schema if you integrate the connector with the {link-prefix}:{link-avro-serialization}#avro-serialization[Avro connector].

`.table.include.list`::
The list of tables from which the connector captures change events.
