In the example that follows, the custom resource is configured to download the following artifacts:

* The {prodname} {connector-name} connector archive.
* The {registry-name-full} archive. The {registry} is an optional component.
Add the {registry} component only if you intend to use Avro serialization with the connector.
* The {prodname} scripting SMT archive and the associated language dependencies that you want to use with the Debezium connector.
The SMT archive and language dependencies are optional components.
Add these components only if you intend to use the {prodname} {link-prefix}:{link-content-based-routing}#content-based-routing[content-based routing SMT] or {link-prefix}:{link-filtering}#message-filtering[filter SMT].
* The {connector-name} JDBC driver, which is required to connect to {connector-name} databases, but is not included in the connector archive.

[source%nowrap,yaml,subs="+attributes,+quotes"]
----
apiVersion: {KafkaConnectApiVersion}
kind: KafkaConnect
metadata:
  name: debezium-kafka-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: {debezium-kafka-version}
  build:
    output:
      type: imagestream
      image: debezium-streams-connect:latest
    plugins:
      - name: debezium-connector-{connector-file}
        artifacts:
          - type: zip
            url: {red-hat-maven-repository}debezium/debezium-connector-{connector-file}/{debezium-version}-redhat-{debezium-build-number}/debezium-connector-{connector-file}-{debezium-version}-redhat-{debezium-build-number}-plugin.zip
          - type: zip
            url: {red-hat-maven-repository}apicurio/apicurio-registry-distro-connect-converter/{registry-maven-version}.redhat-{registry-build-number}/apicurio-registry-distro-connect-converter-{registry-maven-version}.redhat-{registry-build-number}.zip
          - type: zip
            url: {red-hat-maven-repository}debezium/debezium-scripting/{debezium-version}-redhat-{debezium-build-number}/debezium-scripting-{debezium-version}-redhat-{debezium-build-number}.zip
          - type: jar
            url: https://repo1.maven.org/maven2/org/apache/groovy/groovy/{groovy-version}/groovy-{groovy-version}.jar
          - type: jar
            url: https://repo1.maven.org/maven2/org/apache/groovy/groovy-jsr223/{groovy-version}/groovy-jsr223-{groovy-version}.jar
          - type: jar
            url: https://repo1.maven.org/maven2/org/apache/groovy/groovy-json{groovy-version}/groovy-json-{groovy-version}.jar
          - type: jar
            url: https://repo1.maven.org/maven2/com/ibm/db2/jcc/{db2-version}/jcc-{db2-version}.jar

  bootstrapServers: debezium-kafka-cluster-kafka-bootstrap:9093

  ...
----


The following list describes the purpose of select line in the preceding Kafka Connect configuration example:

`strimzi.io/use-connector-resources: "true"`::
Sets the `strimzi.io/use-connector-resources` annotation to `"true"` to enable the Cluster Operator to use `KafkaConnector` resources to configure connectors in this Kafka Connect cluster.

`build`::
The `spec.build` configuration specifies where to store the build image and lists the plug-ins to include in the image, along with the location of the plug-in artifacts.

`output`::
`build.output` specifies the registry in which the newly built image is stored.

`type`::
Specifies the name and image name for the image output.
Valid values for `output.type` are `docker` to push into a container registry such as Docker Hub or Quay, or `imagestream` to push the image to an internal OpenShift ImageStream.
To use an ImageStream, an ImageStream resource must be deployed to the cluster.
For more information about specifying the `build.output` in the KafkaConnect configuration, see the link:{LinkStreamsAPIReference}#type-Build-reference[Build schema reference] in the {NameStreamsAPIReference}.

`plugins`::
The `plugins` configuration lists all of the connectors that you want to include in the Kafka Connect image.
For each entry in the list, specify a plug-in `name`, and information for about the artifacts that are required to build the connector.
Optionally, for each connector plug-in, you can include other components that you want to be available for use with the connector.
For example, you can add Service Registry artifacts, or the {prodname} scripting component.

`plugins.name`:::
Specifies the name (`debezium-connector-{connector-file}`) of the {prodname} Kafka connector.

`plugins.artifacts.type`:::
Specifies the file type of the artifact specified in the `artifacts.url`.
Valid types are `zip`, `tgz`, or `jar`.
+
{prodname} provides connector archives in `.zip` file format.
JDBC driver files are in `.jar` format.
The `type` value of the artifact must match the extension of the file that is referenced in the `url` field.

`plugins.artifacts.url:::
Specifies the addresses of the repository that store artifacts for the required build components.
The OpenShift cluster must have access to the specified server.
The examples provides URLs for the following components:

`debezium-connector`-{connector-file}:::
Specifies the source for the {prodname} Kafka connector artifact.

`apicurio-registry-distro-connect-converter`:::
(Optional) Specifies the source for the {registry} component.
Include the {registry} artifact, only if you want the connector to use Apache Avro to serialize event keys and values with the {registry-name-full}, instead of using the default JSON converter.

`debezium-scripting`:::
(Optional) Specifies the source for the {prodname} scripting SMT archive to use with the connector.
Include the scripting SMT only if you intend to use the {prodname} {link-prefix}:{link-content-based-routing}#content-based-routing[content-based routing SMT] or {link-prefix}:{link-filtering}#message-filtering[filter SMT]
To use the scripting SMT, you must also deploy a JSR 223-compliant scripting implementation, such as groovy.

`groovy`:::
(Optional) Specifies the source for the JAR files of a JSR 223-compliant scripting implementation.
This value is required to use the {prodname} scripting SMT.
+
[IMPORTANT]
====
For each scripting language component, `artifacts.url` must specify the location of a JAR file, and the value of `artifacts.type` must be set to `jar`.
Invalid values cause the connector fails at runtime.
====
+
To enable use of the Apache Groovy language with the scripting SMT, the custom resource in the example retrieves JAR files for the following libraries:
+
- `groovy`
- `groovy-jsr223` (scripting agent)
- `groovy-json` (module for parsing JSON strings)
+
The {prodname} scripting SMT also supports the use of the JSR 223 implementation of GraalVM JavaScript.

`jcc-db2`:::
Specifies the Maven Central location of the IBM {connector-name} Java Common Connectivity (JCC) JDBC driver.
The required driver is not included in the {prodname} {connector-name} connector archive.
=====================================================================
