The connector also provides the following additional snapshot metrics when an incremental snapshot is executed:

[cols="45%a,25%a,30%a",options="header"]
|===
|Attributes |Type |Description

|[[connectors-insnap-metric-chunkid_{context}]]<<connectors-insnap-metric-chunkid_{context}, `ChunkId`>>
|`string`
|The identifier of the current snapshot chunk.

|[[connectors-insnap-metric-chunkfrom_{context}]]<<connectors-insnap-metric-chunkfrom_{context}, `ChunkFrom`>>
|`string`
|The lower bound of the primary key set defining the current chunk.

|[[connectors-insnap-metric-chunkto_{context}]]<<connectors-insnap-metric-chunkto_{context}, `ChunkTo`>>
|`string`
|The upper bound of the primary key set defining the current chunk.

|[[connectors-insnap-metric-tablefrom_{context}]]<<connectors-insnap-metric-tablefrom_{context}, `TableFrom`>>
|`string`
|The lower bound of the primary key set of the currently snapshotted table.

|[[connectors-insnap-metric-tableto_{context}]]<<connectors-insnap-metric-tableto_{context}, `TableTo`>>
|`string`
|The upper bound of the primary key set of the currently snapshotted table.

|===

ifdef::product[]
[IMPORTANT]
====
Incremental snapshots is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. For more information about the support scope of Red Hat Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview[https://access.redhat.com/support/offerings/techpreview].
====
endif::product[]
