ifdef::community[]
[NOTE]
====
This feature is currently in incubating state, i.e. exact semantics, configuration options etc. may change in future revisions, based on the feedback we receive.
Please let us know if you encounter any problems while using this extension.
====
endif::community[]

ifdef::product[]
[IMPORTANT]
====
The use of ad hoc snapshots is a Technology Preview feature.
Technology Preview features are not supported with Red Hat production service-level agreements (SLAs) and might not be functionally complete;
therefore, Red Hat does not recommend implementing any Technology Preview features in production environments.
This Technology Preview feature provides early access to upcoming product innovations, enabling you to test functionality and provide feedback during the development process.
For more information about support scope, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
endif::product[]

By default, a connector runs an initial snapshot operation only after it starts for the first time.
Following this initial snapshot, the snapshot process is not repeated, and the connector captures data for subsequent change events through streaming only.

However, in some situations the data that the connector obtained during the initial snapshot might become stale, lost, or incomplete.
To provide a mechanism for recapturing table data, {prodname} includes an option to perform ad hoc snapshots.
The following changes in a database might be cause for performing an ad hoc snapshot:

* The connector configuration is modified to capture a different set of tables.
* Kafka topics are deleted and must be rebuilt.
* Data corruption occurs due to a configuration error or some other problem.

You can re-run a snapshot for a table for which you previously captured a snapshot by initiating a so-called _ad-hoc snapshot_.
Ad hoc snapshots require the use of {link-prefix}:{link-signalling}#sending-signals-to-a-debezium-connector[signaling tables].
You initiate an ad hoc snapshot by sending a signal request to the {prodname} signaling table.

When you initiate an ad hoc snapshot of an existing table, the connector appends content to the topic that already exists for the table.
If a previously existing topic was removed, {prodname} can create a topic automatically if xref:{link-topic-auto-creation}#customizing-debezium-automatically-created-topics[automatic topic creation] is enabled.

Each signal specifies the tables to include in the snapshot.
An ad hoc snapshot can recapture the entire contents of the database, or capture only a subset of the tables in the database.

You specify the tables to capture by listing them in a signal message that you send to the signaling table.
The signal is named `execute-snapshot` and accepts messages in the following format:

.Example of an ad hoc snapshot signal record
[cols="2,2,6",options="header"]
|===
|Field | Default | Value

|`type`
|`incremental`
| Specifies the type of snapshot that you want to run. +
Currently, you can request only xref:{context}-incremental-snapshots[`incremental` snapshots].


|`data-collections`
|_N/A_
| An array that contains the fully-qualified names of the tables to be snapshotted. +
The format of the names is the same as for {link-prefix}:{context}-property-signal-data-collection[signal.data.collection] configuration option.

|===

.Triggering an ad hoc snapshot

You initiate an ad hoc snapshot by adding a signaling table entry with the `execute-snapshot` signal type.
After the connector processes the message, it starts the snapshot operation.
The operation reads the first and last primary key values and uses those values as the start and end point for each table.

Currently, the `execute-snapshot` action type triggers xref:debezium-signaling-incremental-snapshots[incremental snapshots] only.

.Prerequisites

* xref:{link-signalling}#debezium-enabling-signaling"[Signaling is enabled].

An example of the signal to be triggered is this:

[source,sql,indent=0,subs="+attributes"]
----
INSERT INTO myschema.debezium_signal VALUES('ad-hoc-1', 'execute-snapshot', '{"data-collections": ["schema1.table1", "schema1.table2"]}')
----
