{prodname} provides a set of `signal.*` properties that control how the connector interacts with the Kafka signals topic.

The following table describes the Kafka `signal` properties.

.Kafka signals configuration properties
[cols="33%a,17%a,50%a",options="header",subs="+attributes"]
|===
|Property |Default |Description
|[[{context}-property-signal-kafka-topic]]<<{context}-property-signal-kafka-topic, `+signal.kafka.topic+`>>
|<topic.prefix>-signal
|The name of the Kafka topic that the connector monitors for ad hoc signals.
[NOTE]
====
In case automatic topic creation is disabled, you need to create the topic with one partition to preserve the signals ordering.
====

|[[{context}-property-signal-kafka-groupId]]<<{context}-property-signal-kafka-groupId, `+signal.kafka.groupId+`>>
|kafka-signal
|The name of the group id used in the Kafka consumer.

|[[{context}-property-signal-kafka-bootstrap-servers]]<<{context}-property-signal-kafka-bootstrap-servers, `+signal.kafka.bootstrap.servers+`>>
|No default
|A list of host/port pairs that the connector uses for establishing an initial connection to the Kafka cluster. 
Each pair references the Kafka cluster that is used by the {prodname} Kafka Connect process.

|[[{context}-property-signal-kafka-poll-timeout-ms]]<<{context}-property-signal-kafka-poll-timeout-ms, `+signal.kafka.poll.timeout.ms+`>>
|`100`
|An integer value that specifies the maximum number of milliseconds that the connector waits when polling signals. 

|===

[id="debezium-{context}-connector-pass-through-signals-kafka-consumer-configuration-properties"]
=== {prodname} connector pass-through signals Kafka consumer client configuration properties

The {prodname} connector provides for pass-through configuration of the signals Kafka consumer.
Pass-through signals properties begin with the prefix `signals.consumer.*`.
For example, the connector passes properties such as `signal.consumer.security.protocol=SSL` to the Kafka consumer.

As is the case with the xref:{context}-pass-through-database-history-properties-for-configuring-producer-and-consumer-clients[pass-through properties for database schema history clients], {prodname} strips the prefixes from the properties before it passes them to the Kafka signals consumer.