{prodname} provides a set of `signal.*` properties that control how the connector interacts with the Kafka signals topic.

The following table describes the Kafka `signal` properties.

.Kafka signals configuration properties
[cols="33%a,17%a,50%a",options="header",subs="+attributes"]
|===
|Property |Default |Description
|[[{context}-property-signal-kafka-topic]]<<{context}-property-signal-kafka-topic, `+signal.kafka.topic+`>>
|<topic.prefix>-signal
|The name of the Kafka topic that the connector monitors for ad hoc signals.
[NOTE]
====
If {link-prefix}:{link-topic-auto-creation}#topic-auto-create-config[automatic topic creation] is disabled, you must manually create the required signaling topic.
A signaling topic is required to preserve signal ordering.
The signaling topic must have a single partition.
====

|[[{context}-property-signal-kafka-groupId]]<<{context}-property-signal-kafka-groupId, `+signal.kafka.groupId+`>>
|kafka-signal
|The name of the group ID that is used by Kafka consumers.

|[[{context}-property-signal-kafka-bootstrap-servers]]<<{context}-property-signal-kafka-bootstrap-servers, `+signal.kafka.bootstrap.servers+`>>
|No default
|A list of the host and port pairs that the connector uses to establish its initial connection to the Kafka cluster.
Each pair references the Kafka cluster that is used by the {prodname} Kafka Connect process.

|[[{context}-property-signal-kafka-poll-timeout-ms]]<<{context}-property-signal-kafka-poll-timeout-ms, `+signal.kafka.poll.timeout.ms+`>>
|`100`
|An integer value that specifies the maximum number of milliseconds that the connector waits when polling signals.

|[[{context}-kafka-consumer-offset-commit-enabled]]<<{context}-kafka-consumer-offset-commit-enabled, `+kafka.consumer.offset.commit.enabled+`>>
|`false`
|Specifies whether the connector processes signal requests that the signaling topic receives while the connector is off-line.
Choose one of the following settings:

`false`:: {prodname} processes only signals that are sent while the connector is running.
When the connector is unavailable, the Kafka consumer does not commit an offset after it reads signals received by the signaling topic.
As a result, after the connector restarts, it processes only signals that it receives after the restart.
Earlier signals are ignored, and are effectively lost.
`true`:: Enables {prodname} to process signals that are sent while the connector is offline, helping to ensure At-Least-Once delivery.
The Kakfa consumer for the signaling topic commits a topic offset whenever it reads a signal, so that it maintains a persistent history of signals that the signaling topic receives while offline.
When you restart the connector, it resumes processing from the last stored position, and not just from the offset of the most recent request since the restart.
 

|===
