/*
 * Copyright Debezium Authors.
 *
 * Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */

package io.debezium.connector.postgresql.connection;

import java.nio.ByteBuffer;

/**
 * A class that is able to deserialize/decode binary representation of replication message generated by
 * logical decoding plugin. There is usually one implementation per decoding plugin.
 * 
 * @author Jiri Pechanec
 *
 */
public interface MessageDecoder {

    /**
     * Deserializes binary representation of replication message into a logical Java class implementation
     * 
     * @param buffer - binary representation of replication message
     * @return Java class encapsulating decoded message
     */
    ReplicationMessage deserializeMessage(ByteBuffer buffer);
}