// Category: cdc-using
// Type: assembly
// ModuleID: emitting-change-event-records-in-cloudevents-format
// Title: Emitting change event records in CloudEvents format
[id="exporting-cloud-events"]
= Exporting CloudEvents

:toc:
:toc-placement: macro
:linkattrs:
:icons: font
:source-highlighter: highlight.js

toc::[]

link:https://cloudevents.io/[CloudEvents] is a specification for describing event data in a common way. Its aim is to provide interoperability across services, platforms and systems. {prodname} enables you to configure a MongoDB, MySQL, PostgreSQL, or SQL Server connector to emit change event records that conform to the CloudEvents specification. 

ifdef::community[]
[NOTE]
====
Support for CloudEvents is in an incubating state. This means that exact semantics, configuration options, and other details may change in future revisions based on feedback.
Please let us know your specific requirements or if you encounter any problems while using this feature.
====
endif::community[]

ifdef::product[]
[IMPORTANT]
====
Emitting change event records in CloudEvents format is a Technology Preview feature. Technology Preview features are not supported with Red Hat production service-level agreements (SLAs) and might not be functionally complete; therefore, Red Hat does not recommend implementing any Technology Preview features in production environments. This Technology Preview feature provides early access to upcoming product innovations, enabling you to test functionality and provide feedback during the development process. For more information about support scope, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
endif::product[]

The CloudEvents specification defines: 

* A set of standardized event attributes
* Rules for defining custom attributes
* Encoding rules for mapping event formats to serialized representations such as JSON or Avro
* Protocol bindings for transport layers such as Apache Kafka, HTTP or AMQP

To configure a {prodname} connector to emit change event records that conform to the CloudEvents specification, {prodname} provides the `io.debezium.converters.CloudEventsConverter`, which is a Kafka Connect message converter. 

Currently, only structured mapping mode is supported. The CloudEvents change event envelope can be JSON or Avro and each envelope type supports JSON or Avro as the `data` format. It is expected that a future {prodname} release will support binary mapping mode. 

// Type: concept
// ModuleID: example-change-event-records-in-cloudevents-format
// Title: Example change event records in CloudEvents format
== Example event format

The following example shows what a CloudEvents change event record emitted by a PostgreSQL connector looks like. In this example, the PostgreSQL connector is configured to use JSON as the CloudEvents format envelope and also as the `data` format.  

[source,json,indent=0]
----
{
  "id" : "name:test_server;lsn:29274832;txId:565",   <1>
  "source" : "/debezium/postgresql/test_server",     <2>
  "specversion" : "1.0",                             <3>
  "type" : "io.debezium.postgresql.datachangeevent", <4>
  "time" : "2020-01-13T13:55:39.738Z",               <5>
  "datacontenttype" : "application/json",            <6>
  "iodebeziumop" : "r",                              <7>
  "iodebeziumversion" : "1.1.0-SNAPSHOT",            <8>
  "iodebeziumconnector" : "postgresql",
  "iodebeziumname" : "test_server",
  "iodebeziumtsms" : "1578923739738",
  "iodebeziumsnapshot" : "true",
  "iodebeziumdb" : "postgres",
  "iodebeziumschema" : "s1",
  "iodebeziumtable" : "a",
  "iodebeziumtxId" : "565",
  "iodebeziumlsn" : "29274832",
  "iodebeziumxmin" : null,
  "iodebeziumtxid": "565",                           <9>
  "iodebeziumtxtotalorder": "1",
  "iodebeziumtxdatacollectionorder": "1",
  "data" : {                                         <10>
    "before" : null,
    "after" : {
      "pk" : 1,
      "name" : "Bob"
    }
  }
}
----
<1> Unique ID that the connector generates for the change event based on the change event's content. 
<2> The source of the event, which is the logical name of the database as specified by the `database.server.name` property in the connector's configuration. 
<3> The CloudEvents specification version. 
<4> Connector type that generated the change event. The format of this field is `io.debezium._CONNECTOR_TYPE_.datachangeevent`. The value of `_CONNECTOR_TYPE_` is `mongodb`, `mysql`, `postgresql`, or `sqlserver`.
<5> Time of the change in the source database.
<6> Describes the content type of the `data` attribute, which is JSON in this example. The only alternative is Avro. 
<7> An operation identifier. Possible values are `r` for read, `c` for create, `u` for update, or `d` for delete. 
<8> All `source` attributes that are known from {prodname} change events are mapped to CloudEvents extension attributes by using the `iodebezium` prefix for the attribute name.
<9> When enabled in the connector, each `transaction` attribute that is known from {prodname} change events is mapped to a CloudEvents extension attribute by using the `iodebeziumtx` prefix for the attribute name.
<10> The actual data change itself. Depending on the operation and the connector, the data might contain `before`, `after` and/or `patch` fields.

The following example also shows what a CloudEvents change event record emitted by a PostgreSQL connector looks like. In this example, the PostgreSQL connector is again configured to use JSON as the CloudEvents format envelope, but this time the connector is configured to use Avro for the `data` format. 

[source,json,indent=0]
----
{
  "id" : "name:test_server;lsn:33227720;txId:578",
  "source" : "/debezium/postgresql/test_server",
  "specversion" : "1.0",
  "type" : "io.debezium.postgresql.datachangeevent",
  "time" : "2020-01-13T14:04:18.597Z",
  "datacontenttype" : "application/avro",            <1>
  "dataschema" : "http://my-registry/schemas/ids/1", <2>
  "iodebeziumop" : "r",
  "iodebeziumversion" : "1.1.0-SNAPSHOT",
  "iodebeziumconnector" : "postgresql",
  "iodebeziumname" : "test_server",
  "iodebeziumtsms" : "1578924258597",
  "iodebeziumsnapshot" : "true",
  "iodebeziumdb" : "postgres",
  "iodebeziumschema" : "s1",
  "iodebeziumtable" : "a",
  "iodebeziumtxId" : "578",
  "iodebeziumlsn" : "33227720",
  "iodebeziumxmin" : null,
  "iodebeziumtxid": "578",
  "iodebeziumtxtotalorder": "1",
  "iodebeziumtxdatacollectionorder": "1",
  "data" : "AAAAAAEAAgICAg=="                        <3>
}
----
<1> Indicates that the `data` attribute contains Avro binary data.
<2> URI of the schema to which the Avro data adheres.
<3> The `data` attribute contains base64-encoded Avro binary data.

It is also possible to use Avro for the envelope as well as the `data` attribute.

// Type: concept
// ModuleID: example-of-configuring-cloudevents-converter
// Title: Example of configuring `CloudEventsConverter`
== Example configuration

Configure `io.debezium.converters.CloudEventsConverter` in your {prodname} connector configuration. Following is an example of configuring `CloudEventConverter` to emit change event records that:

* Use JSON as the envelope
* Contain Avro data that adheres to the schema at http://schema-registry:8081 

In this example, you could omit the specification of `serializer.type` because `json` is the default. 

[source,json,indent=0]
----
...
"value.converter": "io.debezium.converters.CloudEventsConverter",
"value.converter.serializer.type" : "json",
"value.converter.data.serializer.type" : "avro",
"value.converter.avro.schema.registry.url": "http://schema-registry:8081"
...
----

`CloudEventsConverter` converts Kafka record values. In the same connector configuration, you can specify `key.converter` if you want to operate on record keys, for example you might specify `StringConverter`, `LongConverter`, `JsonConverter`, or `AvroConverter`.

// Type: reference
// ModuleID: cloudeventsconverter-configuration-properties
// Title: `CloudEventsConverter` configuration properties
[[cloud-events-converter-configuration-options]]
== Configuration properties

When you configure a {prodname} connector to use the CloudEvent converter you can specify the following properties. 


[cols="30%a,25%a,45%a"]
|===
|Property
|Default
|Description

[id="cloud-events-converter-serializer-type"]
|{link-prefix}:{link-cloud-events}#cloud-events-converter-serializer-type[`serializer.type`]
|`json`
|The encoding type to use for the CloudEvents envelope structure. The value can be `json` or `avro`.

[id="cloud-events-converter-data-serializer-type"]
|{link-prefix}:{link-cloud-events}#cloud-events-converter-data-serializer-type[`data.serializer.type`]
|`json`
|The encoding type to use for the `data` attribute. The value can be `json` or `avro`.

[id="cloud-events-converter-json"]
|{link-prefix}:{link-cloud-events}#cloud-events-converter-json[`json. \...`]
|N/A
|Any configuration properties to be passed through to the underlying converter when using JSON. The `json.` prefix is removed. 

[id="cloud-events-converter-avro"]
|{link-prefix}:{link-cloud-events}#cloud-events-converter-avro[`avro. \...`]
|N/A
|Any configuration properties to be passed through to the underlying converter when using Avro. The `avro.` prefix is removed. For example, for Avro `data`, you would specify the `avro.schema.registry.url` property. 

|===
