version: '3.1'

services:
  app:
    container_name: testsuite
    image: testsuite:latest
    volumes: 
      # For specific LOG directory set env variable HOST_LOG_DIR
      - "${HOST_LOG_DIR:-./testsuite-log}:/testsuite/logs:rw"
    restart: always
    ports: 
      - 3306:3306
    environment:
      - OCP_PROJECT_DEBEZIUM=debezium-test
      - OCP_PROJECT_MYSQL=debezium-test-mysql
      - OCP_PROJECT_POSTGRESQL=debezium-test-postgresql
      - OCP_PROJECT_SQLSERVER=debezium-test-sqlserver
      - OCP_PROJECT_MONGO=debezium-test-mongo
      - OCP_PROJECT_DB2=debezium-test-db2
      - DBZ_GIT_REPOSITORY=https://github.com/debezium/debezium.git
      - DBZ_GIT_BRANCH=main
      - PRODUCT_BUILD=false
      - STRZ_GIT_REPOSITORY=https://github.com/strimzi/strimzi-kafka-operator.git
      - STRZ_GIT_BRANCH=main
      - TEST_VERSION_KAFKA=2.7.0
      - OCP_USERNAME=debezium
      - OCP_PASSWORD=BlueSlon42
      - OCP_URL=https://api.cluster.dbz.cechacek.net:6443
      - TEST_WAIT_SCALE=1
      - TEST_APICURIO_REGISTRY=false
      - DBZ_CONNECT_IMAGE=
      - OCP_STRIMZI_DOWNSTREAM_URL=http://rcm-guest.app.eng.bos.redhat.com/rcm-guest/staging/amq/AMQ-STREAMS-1.6.2.CR1/amq-streams-1.6.2.CR1-ocp-install-examples.zip
      - DELETE_PROJECTS=true
