CREATE TABLE `BOOLEAN_DEFAULT_TEST` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `b1` BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
INSERT INTO BOOLEAN_DEFAULT_TEST(id) VALUE (1);
