CREATE TABLE `dbz4180` (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  a NUMERIC(10, 2) NOT NULL DEFAULT 1.23,
  b DECIMAL(10, 3) NOT NULL DEFAULT 2.321,
  c VARCHAR(255) NULL DEFAULT 'default mysql strategy',
  d INT NULL DEFAULT '100',
  e DATETIME NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
INSERT INTO `dbz4180`(a, b, c, d)
VALUES (1.33, -2.111 , 'topic strategy', 99);

CREATE TABLE `dbz_4180_00` (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  a NUMERIC(10, 2) NOT NULL DEFAULT 1.23,
  b DECIMAL(10, 3) NOT NULL DEFAULT 2.321,
  c VARCHAR(255) NULL DEFAULT 'shard 0',
  d INT NULL DEFAULT '100',
  e DATETIME NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `dbz_4180_01` (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  a NUMERIC(10, 2) NOT NULL DEFAULT 1.23,
  b DECIMAL(10, 3) NOT NULL DEFAULT 2.321,
  c VARCHAR(255) NULL DEFAULT 'shard 1',
  d INT NULL DEFAULT '100',
  e DATETIME NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `dbz5743中文` (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  a NUMERIC(10, 2) NOT NULL DEFAULT 1.23,
  b DECIMAL(10, 3) NOT NULL DEFAULT 2.321,
  c VARCHAR(255) NULL DEFAULT 'default mysql strategy',
  d INT NULL DEFAULT '100',
  e DATETIME NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
INSERT INTO `dbz5743中文`(a, b, c, d)
VALUES (1.33, -2.111 , 'topic strategy', 99);