/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":debezium-core"))
    api(libs.org.antlr.antlr4.runtime)
    testImplementation(project(":debezium-core"))
    testImplementation(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.assertj.assertj.core)
    compileOnly(libs.org.slf4j.slf4j.api)
}

description = "Debezium ANTLR DDL parsers"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
