name: "Build MariaDB"
description: "Builds the Debezium MariaDB connector"

inputs:
  maven-cache-key:
    description: "The maven build cache key"
    required: true
  profile:
    description: "The MariaDB build profile to use"
    required: false
    default: "mariadb-ci"
  shell:
    description: "The shell to use"
    required: false
    default: bash

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-java

    - uses: ./.github/actions/maven-cache
      with:
        key: ${{ inputs.maven-cache-key }}

    - name: Build MariaDB connector (MariaDB - ${{ inputs.profile }})
      shell: ${{ inputs.shell }}
      run: >
        ./mvnw clean install -B -pl debezium-connector-mariadb -am
        -P${{ inputs.profile }}
        -Dcheckstyle.skip=true
        -Dformat.skip=true
        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        -Dmaven.wagon.http.pool=false
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
        -DfailFlakyTests=false
        -Ddebezium.test.mongo.replica.primary.startup.timeout.seconds=120
