name: JDBC Builds
on:
  workflow_call:
    inputs:
      maven-cache-key:
        description: "The cache key to use to restore/save build caches."
        required: true
        type: string
      max-parallel:
        description: "The maximum number of workers to consume, by default uses all available."
        required: false
        type: number

jobs:
  build-jdbc:
    strategy:
      max-parallel: ${{ inputs.max-parallel }}
      fail-fast: false
      matrix:
        # Runs JDBC sink tests based on specific target platforms concurrently
        test-tags: [ "it-mysql,e2e-mysql", "it-postgresql,e2e-postgresql", "it-sqlserver,e2e-sqlserver", "it-singlestore,e2e-singlestore", "it-cockroachdb,e2e-cockroachdb", "it-starrocks,e2e-starrocks"]
        sink-framework: [ "false", "true" ]
    name: JDBC - ${{ matrix.test-tags }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build JDBC - ${{ matrix.test-tags }} - ${{ matrix.sink-framework == 'true' && 'Shared Sink Framework' || 'Legacy Mode' }}
        uses: ./.github/actions/build-debezium-jdbc
        with:
          maven-cache-key: ${{ inputs.maven-cache-key }}-${{ hashFiles('**/pom.xml') }}
          tags: ${{ matrix.test-tags }}
          sink-framework: ${{ matrix.sink-framework }}
