name: MariaDB Builds
on:
  workflow_call:
    inputs:
      maven-cache-key:
        description: "The cache key to use to restore/save build caches."
        required: true
        type: string
      max-parallel:
        description: "The maximum number of workers to consume, by default uses all available."
        required: false
        type: number

jobs:
  build-mariadb:
    strategy:
      max-parallel: ${{ inputs.max-parallel }}
      fail-fast: false
      matrix:
        profile: [ 'mariadb-ci', 'mariadb-ci-gtids', 'mariadb-ci-ssl' ]
    name: MariaDB - ${{ matrix.profile }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build MariaDB - ${{ matrix.profile }}
        uses: ./.github/actions/build-debezium-mariadb
        with:
          maven-cache-key: ${{ inputs.maven-cache-key }}-${{ hashFiles('**/pom.xml') }}
          profile: ${{ matrix.profile }}

