name: Build Incubator Workflow

on:
  push:
    paths:
      - 'debezium-core/**'
      - 'debezium-api/**'
  pull_request:
    paths:
      - 'debezium-core/**'
      - 'debezium-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Core
        uses: actions/checkout@v2
        with:
          path: core
      - name: Checkout Incubator Repository
        uses: actions/checkout@v2
        with:
          repository: debezium/debezium-incubator
          path: incubator
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build Debezium Core
        run: mvn clean install -f core/pom.xml -DskipTests -DskipITs -Dformat.formatter.goal=validate -Dformat.imports.goal=check
      - name: Build Debezium Incubator
        run: mvn -B clean install -f incubator/pom.xml -Passembly -Dformat.formatter.goal=validate -Dformat.imports.goal=check -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
